MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DPA1*01:03:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [130]                  [60.2/58.7]         2.4478 ± 0 
2              [130]                  [60.2/57.6]         2.5311 ± 0 
3              [131]                  [60.2/57.6]         2.5326 ± 0 
4              [131]                  [60.2/59.6]         2.5377 ± 0 
5              [131]                  [59.2/58.7]         3.0569 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 2.4478 ± 0, Mean Tm: 59.5 ± 1.0 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DPA1*01:03:01:01_0    2.4478        130       60.2 / 58.7    5'-TAGACCCCACAACATGCGCCCT-3' / 5'-TCCTCCTGAGCACTCACCCTTGA-3'


* Template 1: DPA1*01:03:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*01:03:01:01_0_fp + DPA1*01:03:01:01_0_rp ==> T1: DPA1*01:03:01:01

           PPC = 96.9%, Size = 130 bp, GC content = 55.4%
           FP: 3'ΔG = -3.8(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -1.7(kcal/mol), Tm = 58.7 (°C)
           Binding sites: 21(22/22) ... 150(23/23)
         
         >>>DPA1*01:03:01:01_0_fp
            1                    22
         5' TAGACCCCACAACATGCGCCCT 3'
            ||||||||||||||||||||||                                                   150
         5' TAGACCCCACAACATGCGCCCTgaagacagaatgt...ggagctggggccaTCAAGGGTGAGTGCTCAGGAGGA 3'
            21                                                 |||||||||||||||||||||||
                                                            3' TCAAGGGTGAGTGCTCAGGAGGA 5'
                                                               23                    1
                                                                 DPA1*01:03:01:01_0_rp<<<
         

         >11_DPA1*01:03:01:01_0_fp_DPA1*01:03:01:01_0_rp_T_1_DPA1*01:03:01:01 
         TAGACCCCACAACATGCGCCCTgaagacagaatgttccatatcagagctgtgatcttgagagccctctccttggct
         ttcctgctgagtctccgaggagctggggccaTCAAGGGTGAGTGCTCAGGAGGA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 2.5311 ± 0, Mean Tm: 58.9 ± 1.8 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DPA1*01:03:01:01_1    2.5311        130       60.2 / 57.6    5'-TAGACCCCACAACATGCGCCCT-3' / 5'-TCCTCCTGAGCACTCACCCTTG-3'


* Template 1: DPA1*01:03:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*01:03:01:01_1_fp + DPA1*01:03:01:01_1_rp ==> T1: DPA1*01:03:01:01

           PPC = 100.0%, Size = 130 bp, GC content = 55.4%
           FP: 3'ΔG = -3.8(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -2.3(kcal/mol), Tm = 57.6 (°C)
           Binding sites: 21(22/22) ... 150(22/22)
         
         >>>DPA1*01:03:01:01_1_fp
            1                    22
         5' TAGACCCCACAACATGCGCCCT 3'
            ||||||||||||||||||||||                                                  150
         5' TAGACCCCACAACATGCGCCCTgaagacagaatgt...gagctggggccatCAAGGGTGAGTGCTCAGGAGGA 3'
            21                                                 ||||||||||||||||||||||
                                                            3' CAAGGGTGAGTGCTCAGGAGGA 5'
                                                               22                   1
                                                                 DPA1*01:03:01:01_1_rp<<<
         

         >2_DPA1*01:03:01:01_1_fp_DPA1*01:03:01:01_1_rp_T_1_DPA1*01:03:01:01 
         TAGACCCCACAACATGCGCCCTgaagacagaatgttccatatcagagctgtgatcttgagagccctctccttggct
         ttcctgctgagtctccgaggagctggggccatCAAGGGTGAGTGCTCAGGAGGA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 2.5326 ± 0, Mean Tm: 58.9 ± 1.8 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DPA1*01:03:01:01_2    2.5326        131       60.2 / 57.6    5'-TAGACCCCACAACATGCGCCCT-3' / 5'-GTCCTCCTGAGCACTCACCCTT-3'


* Template 1: DPA1*01:03:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*01:03:01:01_2_fp + DPA1*01:03:01:01_2_rp ==> T1: DPA1*01:03:01:01

           PPC = 100.0%, Size = 131 bp, GC content = 55.7%
           FP: 3'ΔG = -3.8(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -2.6(kcal/mol), Tm = 57.6 (°C)
           Binding sites: 21(22/22) ... 151(22/22)
         
         >>>DPA1*01:03:01:01_2_fp
            1                    22
         5' TAGACCCCACAACATGCGCCCT 3'
            ||||||||||||||||||||||                                                  151
         5' TAGACCCCACAACATGCGCCCTgaagacagaatgt...agctggggccatcAAGGGTGAGTGCTCAGGAGGAC 3'
            21                                                 ||||||||||||||||||||||
                                                            3' AAGGGTGAGTGCTCAGGAGGAC 5'
                                                               22                   1
                                                                 DPA1*01:03:01:01_2_rp<<<
         

         >7_DPA1*01:03:01:01_2_fp_DPA1*01:03:01:01_2_rp_T_1_DPA1*01:03:01:01 
         TAGACCCCACAACATGCGCCCTgaagacagaatgttccatatcagagctgtgatcttgagagccctctccttggct
         ttcctgctgagtctccgaggagctggggccatcAAGGGTGAGTGCTCAGGAGGAC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 2.5377 ± 0, Mean Tm: 59.9 ± 0.4 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DPA1*01:03:01:01_3    2.5377        131       60.2 / 59.6    5'-TAGACCCCACAACATGCGCCCT-3' / 5'-GTCCTCCTGAGCACTCACCCTTGA-3'


* Template 1: DPA1*01:03:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*01:03:01:01_3_fp + DPA1*01:03:01:01_3_rp ==> T1: DPA1*01:03:01:01

           PPC = 93.9%, Size = 131 bp, GC content = 55.7%
           FP: 3'ΔG = -3.8(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -1.7(kcal/mol), Tm = 59.6 (°C)
           Binding sites: 21(22/22) ... 151(24/24)
         
         >>>DPA1*01:03:01:01_3_fp
            1                    22
         5' TAGACCCCACAACATGCGCCCT 3'
            ||||||||||||||||||||||                                                  151
         5' TAGACCCCACAACATGCGCCCTgaagacagaatg...gagctggggccaTCAAGGGTGAGTGCTCAGGAGGAC 3'
            21                                               ||||||||||||||||||||||||
                                                          3' TCAAGGGTGAGTGCTCAGGAGGAC 5'
                                                             24                     1
                                                                 DPA1*01:03:01:01_3_rp<<<
         

         >24_DPA1*01:03:01:01_3_fp_DPA1*01:03:01:01_3_rp_T_1_DPA1*01:03:01:01 
         TAGACCCCACAACATGCGCCCTgaagacagaatgttccatatcagagctgtgatcttgagagccctctccttggct
         ttcctgctgagtctccgaggagctggggccaTCAAGGGTGAGTGCTCAGGAGGAC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 3.0569 ± 0, Mean Tm: 59.0 ± 0.3 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DPA1*01:03:01:01_4    3.0569        131       59.2 / 58.7    5'-ATAGACCCCACAACATGCGCCC-3' / 5'-TCCTCCTGAGCACTCACCCTTGA-3'


* Template 1: DPA1*01:03:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*01:03:01:01_4_fp + DPA1*01:03:01:01_4_rp ==> T1: DPA1*01:03:01:01

           PPC = 96.9%, Size = 131 bp, GC content = 55.0%
           FP: 3'ΔG = -4.7(kcal/mol), Tm = 59.2 (°C)
           RP: 3'ΔG = -1.7(kcal/mol), Tm = 58.7 (°C)
           Binding sites: 20(22/22) ... 150(23/23)
         
         >>>DPA1*01:03:01:01_4_fp
            1                    22
         5' ATAGACCCCACAACATGCGCCC 3'
            ||||||||||||||||||||||                                                   150
         5' ATAGACCCCACAACATGCGCCCtgaagacagaatg...ggagctggggccaTCAAGGGTGAGTGCTCAGGAGGA 3'
            20                                                 |||||||||||||||||||||||
                                                            3' TCAAGGGTGAGTGCTCAGGAGGA 5'
                                                               23                    1
                                                                 DPA1*01:03:01:01_4_rp<<<
         

         >20_DPA1*01:03:01:01_4_fp_DPA1*01:03:01:01_4_rp_T_1_DPA1*01:03:01:01 
         ATAGACCCCACAACATGCGCCCtgaagacagaatgttccatatcagagctgtgatcttgagagccctctccttggc
         tttcctgctgagtctccgaggagctggggccaTCAAGGGTGAGTGCTCAGGAGGA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    