MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DQA1*06:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [137]                  [58.7/59.8]         8.4860 ± 0 
2              [136]                  [58.7/58.7]         8.5816 ± 0 
3              [152]                  [60.4/59.8]         8.5953 ± 0 
4              [151]                  [60.4/58.7]         8.6910 ± 0 
5              [137]                  [57.5/59.8]         8.7352 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 8.4860 ± 0, Mean Tm: 59.3 ± 0.8 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                         

T1: DQA1*06:01_0    8.486         137       58.7 / 59.8    5'-TGTCGTTCCGTCATGATTGCCTCA-3' / 5'-ACCACCGGAGATATCCGAAAAGCTTCA-3'


* Template 1: DQA1*06:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*06:01_0_fp + DQA1*06:01_0_rp ==> T1: DQA1*06:01

           PPC = 91.7%, Size = 137 bp, GC content = 34.3%
           FP: 3'ΔG = -2.5(kcal/mol), Tm = 58.7 (°C)
           RP: 3'ΔG = -1.7(kcal/mol), Tm = 59.8 (°C)
           Binding sites: 21(24/24) ... 157(27/27)
         
         >>>DQA1*06:01_0_fp
            1                      24
         5' TGTCGTTCCGTCATGATTGCCTCA 3'
            ||||||||||||||||||||||||                                                 157
         5' TGTCGTTCCGTCATGATTGCCTCAaaaattagtg...gaacaactttTGAAGCTTTTCGGATATCTCCGGTGGT 3'
            21                                             |||||||||||||||||||||||||||
                                                        3' TGAAGCTTTTCGGATATCTCCGGTGGT 5'
                                                           27                        1
                                                                       DQA1*06:01_0_rp<<<
         

         >15_DQA1*06:01_0_fp_DQA1*06:01_0_rp_T_1_DQA1*06:01 
         TGTCGTTCCGTCATGATTGCCTCAaaaattagtgaggtttccatcagtggataattttttattattaaaaatttat
         gaagtgtcattctcaaatttccctgaacaactttTGAAGCTTTTCGGATATCTCCGGTGGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 8.5816 ± 0, Mean Tm: 58.7 ± 0.0 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                        

T1: DQA1*06:01_1    8.5816        136       58.7 / 58.7    5'-TGTCGTTCCGTCATGATTGCCTCA-3' / 5'-CCACCGGAGATATCCGAAAAGCTTCA-3'


* Template 1: DQA1*06:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*06:01_1_fp + DQA1*06:01_1_rp ==> T1: DQA1*06:01

           PPC = 94.3%, Size = 136 bp, GC content = 34.6%
           FP: 3'ΔG = -2.5(kcal/mol), Tm = 58.7 (°C)
           RP: 3'ΔG = -1.7(kcal/mol), Tm = 58.7 (°C)
           Binding sites: 21(24/24) ... 156(26/26)
         
         >>>DQA1*06:01_1_fp
            1                      24
         5' TGTCGTTCCGTCATGATTGCCTCA 3'
            ||||||||||||||||||||||||                                                156
         5' TGTCGTTCCGTCATGATTGCCTCAaaaattagtg...gaacaactttTGAAGCTTTTCGGATATCTCCGGTGG 3'
            21                                             ||||||||||||||||||||||||||
                                                        3' TGAAGCTTTTCGGATATCTCCGGTGG 5'
                                                           26                       1
                                                                       DQA1*06:01_1_rp<<<
         

         >13_DQA1*06:01_1_fp_DQA1*06:01_1_rp_T_1_DQA1*06:01 
         TGTCGTTCCGTCATGATTGCCTCAaaaattagtgaggtttccatcagtggataattttttattattaaaaatttat
         gaagtgtcattctcaaatttccctgaacaactttTGAAGCTTTTCGGATATCTCCGGTGG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 8.5953 ± 0, Mean Tm: 60.1 ± 0.4 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                          

T1: DQA1*06:01_2    8.5953        152       60.4 / 59.8    5'-GCCTGGAGGTCTCTATGTCGTTCCG-3' / 5'-ACCACCGGAGATATCCGAAAAGCTTCA-3'


* Template 1: DQA1*06:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*06:01_2_fp + DQA1*06:01_2_rp ==> T1: DQA1*06:01

           PPC = 94.6%, Size = 152 bp, GC content = 36.8%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 60.4 (°C)
           RP: 3'ΔG = -1.7(kcal/mol), Tm = 59.8 (°C)
           Binding sites: 6(25/25) ... 157(27/27)
         
         >>>DQA1*06:01_2_fp
            1                       25
         5' GCCTGGAGGTCTCTATGTCGTTCCG 3'
            |||||||||||||||||||||||||                                               157
         5' GCCTGGAGGTCTCTATGTCGTTCCGtcatgattg...aacaactttTGAAGCTTTTCGGATATCTCCGGTGGT 3'
            6                                             |||||||||||||||||||||||||||
                                                       3' TGAAGCTTTTCGGATATCTCCGGTGGT 5'
                                                          27                        1
                                                                       DQA1*06:01_2_rp<<<
         

         >6_DQA1*06:01_2_fp_DQA1*06:01_2_rp_T_1_DQA1*06:01 
         GCCTGGAGGTCTCTATGTCGTTCCGtcatgattgcctcaaaaattagtgaggtttccatcagtggataatttttta
         ttattaaaaatttatgaagtgtcattctcaaatttccctgaacaactttTGAAGCTTTTCGGATATCTCCGGTGGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 8.6910 ± 0, Mean Tm: 59.6 ± 1.2 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                         

T1: DQA1*06:01_3    8.691         151       60.4 / 58.7    5'-GCCTGGAGGTCTCTATGTCGTTCCG-3' / 5'-CCACCGGAGATATCCGAAAAGCTTCA-3'


* Template 1: DQA1*06:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*06:01_3_fp + DQA1*06:01_3_rp ==> T1: DQA1*06:01

           PPC = 97.2%, Size = 151 bp, GC content = 37.1%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 60.4 (°C)
           RP: 3'ΔG = -1.7(kcal/mol), Tm = 58.7 (°C)
           Binding sites: 6(25/25) ... 156(26/26)
         
         >>>DQA1*06:01_3_fp
            1                       25
         5' GCCTGGAGGTCTCTATGTCGTTCCG 3'
            |||||||||||||||||||||||||                                                156
         5' GCCTGGAGGTCTCTATGTCGTTCCGtcatgattgc...gaacaactttTGAAGCTTTTCGGATATCTCCGGTGG 3'
            6                                               ||||||||||||||||||||||||||
                                                         3' TGAAGCTTTTCGGATATCTCCGGTGG 5'
                                                            26                       1
                                                                       DQA1*06:01_3_rp<<<
         

         >4_DQA1*06:01_3_fp_DQA1*06:01_3_rp_T_1_DQA1*06:01 
         GCCTGGAGGTCTCTATGTCGTTCCGtcatgattgcctcaaaaattagtgaggtttccatcagtggataatttttta
         ttattaaaaatttatgaagtgtcattctcaaatttccctgaacaactttTGAAGCTTTTCGGATATCTCCGGTGG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 8.7352 ± 0, Mean Tm: 58.6 ± 1.7 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                        

T1: DQA1*06:01_4    8.7352        137       57.5 / 59.8    5'-TGTCGTTCCGTCATGATTGCCTC-3' / 5'-ACCACCGGAGATATCCGAAAAGCTTCA-3'


* Template 1: DQA1*06:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*06:01_4_fp + DQA1*06:01_4_rp ==> T1: DQA1*06:01

           PPC = 88.7%, Size = 137 bp, GC content = 34.3%
           FP: 3'ΔG = -3.4(kcal/mol), Tm = 57.5 (°C)
           RP: 3'ΔG = -1.7(kcal/mol), Tm = 59.8 (°C)
           Binding sites: 21(23/23) ... 157(27/27)
         
         >>>DQA1*06:01_4_fp
            1                     23
         5' TGTCGTTCCGTCATGATTGCCTC 3'
            |||||||||||||||||||||||                                                 157
         5' TGTCGTTCCGTCATGATTGCCTCaaaaattagt...gaacaactttTGAAGCTTTTCGGATATCTCCGGTGGT 3'
            21                                            |||||||||||||||||||||||||||
                                                       3' TGAAGCTTTTCGGATATCTCCGGTGGT 5'
                                                          27                        1
                                                                       DQA1*06:01_4_rp<<<
         

         >25_DQA1*06:01_4_fp_DQA1*06:01_4_rp_T_1_DQA1*06:01 
         TGTCGTTCCGTCATGATTGCCTCaaaaattagtgaggtttccatcagtggataattttttattattaaaaatttat
         gaagtgtcattctcaaatttccctgaacaactttTGAAGCTTTTCGGATATCTCCGGTGGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    