MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DRB1*15:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [132]                  [59.0/60.4]         1.3834 ± 0 
2              [134]                  [59.0/59.6]         1.4114 ± 0 
3              [135]                  [59.0/59.6]         1.4127 ± 0 
4              [147]                  [59.0/59.6]         1.4148 ± 0 
5              [154]                  [59.0/59.5]         1.4964 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 1.3834 ± 0, Mean Tm: 59.7 ± 1.0 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*15:01:01_0    1.3834        132       59.0 / 60.4    5'-TGGTGAGGCTAGGGCTTCAGGT-3' / 5'-TGCTGGCCTGTGCCCTCTTCTT-3'


* Template 1: DRB1*15:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*15:01:01_0_fp + DRB1*15:01:01_0_rp ==> T1: DRB1*15:01:01

           PPC = 100.0%, Size = 132 bp, GC content = 47.7%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.0 (°C)
           RP: 3'ΔG = -1.2(kcal/mol), Tm = 60.4 (°C)
           Binding sites: 2(22/22) ... 133(22/22)
         
         >>>DRB1*15:01:01_0_fp
            1                    22
         5' TGGTGAGGCTAGGGCTTCAGGT 3'
            ||||||||||||||||||||||                                                  133
         5' TGGTGAGGCTAGGGCTTCAGGTatttatgttggag...tgtgtggagaaacAAGAAGAGGGCACAGGCCAGCA 3'
            2                                                  ||||||||||||||||||||||
                                                            3' AAGAAGAGGGCACAGGCCAGCA 5'
                                                               22                   1
                                                                    DRB1*15:01:01_0_rp<<<
         

         >1_DRB1*15:01:01_0_fp_DRB1*15:01:01_0_rp_T_1_DRB1*15:01:01 
         TGGTGAGGCTAGGGCTTCAGGTatttatgttggaggcatcaatacgtgtagtgtgttaaattccagggagtggaag
         aggatacatagggagatggattgtgtggagaaacAAGAAGAGGGCACAGGCCAGCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 1.4114 ± 0, Mean Tm: 59.3 ± 0.4 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*15:01:01_1    1.4114        134       59.0 / 59.6    5'-TGGTGAGGCTAGGGCTTCAGGT-3' / 5'-TTTGCTGGCCTGTGCCCTCTTC-3'


* Template 1: DRB1*15:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*15:01:01_1_fp + DRB1*15:01:01_1_rp ==> T1: DRB1*15:01:01

           PPC = 100.0%, Size = 134 bp, GC content = 47.0%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.0 (°C)
           RP: 3'ΔG = -1.6(kcal/mol), Tm = 59.6 (°C)
           Binding sites: 2(22/22) ... 135(22/22)
         
         >>>DRB1*15:01:01_1_fp
            1                    22
         5' TGGTGAGGCTAGGGCTTCAGGT 3'
            ||||||||||||||||||||||                                                  135
         5' TGGTGAGGCTAGGGCTTCAGGTatttatgttggag...tgtggagaaacaaGAAGAGGGCACAGGCCAGCAAA 3'
            2                                                  ||||||||||||||||||||||
                                                            3' GAAGAGGGCACAGGCCAGCAAA 5'
                                                               22                   1
                                                                    DRB1*15:01:01_1_rp<<<
         

         >7_DRB1*15:01:01_1_fp_DRB1*15:01:01_1_rp_T_1_DRB1*15:01:01 
         TGGTGAGGCTAGGGCTTCAGGTatttatgttggaggcatcaatacgtgtagtgtgttaaattccagggagtggaag
         aggatacatagggagatggattgtgtggagaaacaaGAAGAGGGCACAGGCCAGCAAA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 1.4127 ± 0, Mean Tm: 59.3 ± 0.4 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*15:01:01_2    1.4127        135       59.0 / 59.6    5'-TGGTGAGGCTAGGGCTTCAGGT-3' / 5'-CTTTGCTGGCCTGTGCCCTCTT-3'


* Template 1: DRB1*15:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*15:01:01_2_fp + DRB1*15:01:01_2_rp ==> T1: DRB1*15:01:01

           PPC = 100.0%, Size = 135 bp, GC content = 47.4%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.0 (°C)
           RP: 3'ΔG = -1.5(kcal/mol), Tm = 59.6 (°C)
           Binding sites: 2(22/22) ... 136(22/22)
         
         >>>DRB1*15:01:01_2_fp
            1                    22
         5' TGGTGAGGCTAGGGCTTCAGGT 3'
            ||||||||||||||||||||||                                                  136
         5' TGGTGAGGCTAGGGCTTCAGGTatttatgttggag...gtggagaaacaagAAGAGGGCACAGGCCAGCAAAG 3'
            2                                                  ||||||||||||||||||||||
                                                            3' AAGAGGGCACAGGCCAGCAAAG 5'
                                                               22                   1
                                                                    DRB1*15:01:01_2_rp<<<
         

         >13_DRB1*15:01:01_2_fp_DRB1*15:01:01_2_rp_T_1_DRB1*15:01:01 
         TGGTGAGGCTAGGGCTTCAGGTatttatgttggaggcatcaatacgtgtagtgtgttaaattccagggagtggaag
         aggatacatagggagatggattgtgtggagaaacaagAAGAGGGCACAGGCCAGCAAAG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 1.4148 ± 0, Mean Tm: 59.3 ± 0.4 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*15:01:01_3    1.4148        147       59.0 / 59.6    5'-TGGTGAGGCTAGGGCTTCAGGT-3' / 5'-TTTCTCAGCCCCCTTTGCTGGC-3'


* Template 1: DRB1*15:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*15:01:01_3_fp + DRB1*15:01:01_3_rp ==> T1: DRB1*15:01:01

           PPC = 100.0%, Size = 147 bp, GC content = 48.3%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.0 (°C)
           RP: 3'ΔG = -3.5(kcal/mol), Tm = 59.6 (°C)
           Binding sites: 2(22/22) ... 148(22/22)
         
         >>>DRB1*15:01:01_3_fp
            1                    22
         5' TGGTGAGGCTAGGGCTTCAGGT 3'
            ||||||||||||||||||||||                                                  148
         5' TGGTGAGGCTAGGGCTTCAGGTatttatgttggag...gaagagggcacagGCCAGCAAAGGGGGCTGAGAAA 3'
            2                                                  ||||||||||||||||||||||
                                                            3' GCCAGCAAAGGGGGCTGAGAAA 5'
                                                               22                   1
                                                                    DRB1*15:01:01_3_rp<<<
         

         >19_DRB1*15:01:01_3_fp_DRB1*15:01:01_3_rp_T_1_DRB1*15:01:01 
         TGGTGAGGCTAGGGCTTCAGGTatttatgttggaggcatcaatacgtgtagtgtgttaaattccagggagtggaag
         aggatacatagggagatggattgtgtggagaaacaagaagagggcacagGCCAGCAAAGGGGGCTGAGAAA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 1.4964 ± 0, Mean Tm: 59.3 ± 0.4 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*15:01:01_4    1.4964        154       59.0 / 59.5    5'-TGGTGAGGCTAGGGCTTCAGGT-3' / 5'-TGGGCTCTTTCTCAGCCCCCTT-3'


* Template 1: DRB1*15:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*15:01:01_4_fp + DRB1*15:01:01_4_rp ==> T1: DRB1*15:01:01

           PPC = 100.0%, Size = 154 bp, GC content = 49.4%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.0 (°C)
           RP: 3'ΔG = -2.6(kcal/mol), Tm = 59.5 (°C)
           Binding sites: 2(22/22) ... 155(22/22)
         
         >>>DRB1*15:01:01_4_fp
            1                    22
         5' TGGTGAGGCTAGGGCTTCAGGT 3'
            ||||||||||||||||||||||                                                  155
         5' TGGTGAGGCTAGGGCTTCAGGTatttatgttggag...gcacaggccagcaAAGGGGGCTGAGAAAGAGCCCA 3'
            2                                                  ||||||||||||||||||||||
                                                            3' AAGGGGGCTGAGAAAGAGCCCA 5'
                                                               22                   1
                                                                    DRB1*15:01:01_4_rp<<<
         

         >25_DRB1*15:01:01_4_fp_DRB1*15:01:01_4_rp_T_1_DRB1*15:01:01 
         TGGTGAGGCTAGGGCTTCAGGTatttatgttggaggcatcaatacgtgtagtgtgttaaattccagggagtggaag
         aggatacatagggagatggattgtgtggagaaacaagaagagggcacaggccagcaAAGGGGGCTGAGAAAGAGCC
         CA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    