MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DRB1*16:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [130]                  [59.5/57.3]         11.1500 ± 0
2              [130]                  [59.5/58.2]         11.2536 ± 0
3              [130]                  [58.7/58.0]         11.3084 ± 0
4              [130]                  [59.6/59.0]         11.4149 ± 0
5              [131]                  [59.5/57.1]         11.4175 ± 0



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 11.1500 ± 0, Mean Tm: 58.4 ± 1.5 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                          

T1: DRB1*16:01:01_0    11.15         130       59.5 / 57.3    5'-TGTGGAGCAATCAGAAGGTCAATGGC-3' / 5'-TCCCTATGTATCCTCTTCCACTCCCT-3'


* Template 1: DRB1*16:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*16:01:01_0_fp + DRB1*16:01:01_0_rp ==> T1: DRB1*16:01:01

           PPC = 100.0%, Size = 130 bp, GC content = 44.6%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 59.5 (°C)
           RP: 3'ΔG = -2.8(kcal/mol), Tm = 57.3 (°C)
           Binding sites: 13(26/26) ... 142(26/26)
         
         >>>DRB1*16:01:01_0_fp
            1                        26
         5' TGTGGAGCAATCAGAAGGTCAATGGC 3'
            ||||||||||||||||||||||||||                                              142
         5' TGTGGAGCAATCAGAAGGTCAATGGCatttaagag...ttaaattccAGGGAGTGGAAGAGGATACATAGGGA 3'
            13                                             ||||||||||||||||||||||||||
                                                        3' AGGGAGTGGAAGAGGATACATAGGGA 5'
                                                           26                       1
                                                                    DRB1*16:01:01_0_rp<<<
         

         >1_DRB1*16:01:01_0_fp_DRB1*16:01:01_0_rp_T_1_DRB1*16:01:01 
         TGTGGAGCAATCAGAAGGTCAATGGCatttaagagactcatggtgaggctagggcttcaggtatttatgttggagg
         catcaatacgtgtagtgtgttaaattccAGGGAGTGGAAGAGGATACATAGGGA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 11.2536 ± 0, Mean Tm: 58.9 ± 0.9 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                           

T1: DRB1*16:01:01_1    11.2536       130       59.5 / 58.2    5'-TGTGGAGCAATCAGAAGGTCAATGGC-3' / 5'-TCCCTATGTATCCTCTTCCACTCCCTG-3'


* Template 1: DRB1*16:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*16:01:01_1_fp + DRB1*16:01:01_1_rp ==> T1: DRB1*16:01:01

           PPC = 97.3%, Size = 130 bp, GC content = 44.6%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 59.5 (°C)
           RP: 3'ΔG = -3.1(kcal/mol), Tm = 58.2 (°C)
           Binding sites: 13(26/26) ... 142(27/27)
         
         >>>DRB1*16:01:01_1_fp
            1                        26
         5' TGTGGAGCAATCAGAAGGTCAATGGC 3'
            ||||||||||||||||||||||||||                                               142
         5' TGTGGAGCAATCAGAAGGTCAATGGCatttaagag...gttaaattcCAGGGAGTGGAAGAGGATACATAGGGA 3'
            13                                             |||||||||||||||||||||||||||
                                                        3' CAGGGAGTGGAAGAGGATACATAGGGA 5'
                                                           27                        1
                                                                    DRB1*16:01:01_1_rp<<<
         

         >14_DRB1*16:01:01_1_fp_DRB1*16:01:01_1_rp_T_1_DRB1*16:01:01 
         TGTGGAGCAATCAGAAGGTCAATGGCatttaagagactcatggtgaggctagggcttcaggtatttatgttggagg
         catcaatacgtgtagtgtgttaaattcCAGGGAGTGGAAGAGGATACATAGGGA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 11.3084 ± 0, Mean Tm: 58.3 ± 0.5 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                          

T1: DRB1*16:01:01_2    11.3084       130       58.7 / 58.0    5'-TGGAGCAATCAGAAGGTCAATGGCA-3' / 5'-TCTCCCTATGTATCCTCTTCCACTCCC-3'


* Template 1: DRB1*16:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*16:01:01_2_fp + DRB1*16:01:01_2_rp ==> T1: DRB1*16:01:01

           PPC = 94.6%, Size = 130 bp, GC content = 44.6%
           FP: 3'ΔG = -3.6(kcal/mol), Tm = 58.7 (°C)
           RP: 3'ΔG = -3.0(kcal/mol), Tm = 58.0 (°C)
           Binding sites: 15(25/25) ... 144(27/27)
         
         >>>DRB1*16:01:01_2_fp
            1                       25
         5' TGGAGCAATCAGAAGGTCAATGGCA 3'
            |||||||||||||||||||||||||                                               144
         5' TGGAGCAATCAGAAGGTCAATGGCAtttaagaga...taaattccaGGGAGTGGAAGAGGATACATAGGGAGA 3'
            15                                            |||||||||||||||||||||||||||
                                                       3' GGGAGTGGAAGAGGATACATAGGGAGA 5'
                                                          27                        1
                                                                    DRB1*16:01:01_2_rp<<<
         

         >25_DRB1*16:01:01_2_fp_DRB1*16:01:01_2_rp_T_1_DRB1*16:01:01 
         TGGAGCAATCAGAAGGTCAATGGCAtttaagagactcatggtgaggctagggcttcaggtatttatgttggaggca
         tcaatacgtgtagtgtgttaaattccaGGGAGTGGAAGAGGATACATAGGGAGA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 11.4149 ± 0, Mean Tm: 59.3 ± 0.4 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                            

T1: DRB1*16:01:01_3    11.4149       130       59.6 / 59.0    5'-ATGTGGAGCAATCAGAAGGTCAATGGC-3' / 5'-CCCTATGTATCCTCTTCCACTCCCTGG-3'


* Template 1: DRB1*16:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*16:01:01_3_fp + DRB1*16:01:01_3_rp ==> T1: DRB1*16:01:01

           PPC = 100.0%, Size = 130 bp, GC content = 44.6%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 59.6 (°C)
           RP: 3'ΔG = -3.1(kcal/mol), Tm = 59.0 (°C)
           Binding sites: 12(27/27) ... 141(27/27)
         
         >>>DRB1*16:01:01_3_fp
            1                         27
         5' ATGTGGAGCAATCAGAAGGTCAATGGC 3'
            |||||||||||||||||||||||||||                                             141
         5' ATGTGGAGCAATCAGAAGGTCAATGGCatttaaga...gttaaattCCAGGGAGTGGAAGAGGATACATAGGG 3'
            12                                            |||||||||||||||||||||||||||
                                                       3' CCAGGGAGTGGAAGAGGATACATAGGG 5'
                                                          27                        1
                                                                    DRB1*16:01:01_3_rp<<<
         

         >3_DRB1*16:01:01_3_fp_DRB1*16:01:01_3_rp_T_1_DRB1*16:01:01 
         ATGTGGAGCAATCAGAAGGTCAATGGCatttaagagactcatggtgaggctagggcttcaggtatttatgttggag
         gcatcaatacgtgtagtgtgttaaattCCAGGGAGTGGAAGAGGATACATAGGG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 11.4175 ± 0, Mean Tm: 58.3 ± 1.7 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                          

T1: DRB1*16:01:01_4    11.4175       131       59.5 / 57.1    5'-TGTGGAGCAATCAGAAGGTCAATGGC-3' / 5'-CTCCCTATGTATCCTCTTCCACTCCC-3'


* Template 1: DRB1*16:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*16:01:01_4_fp + DRB1*16:01:01_4_rp ==> T1: DRB1*16:01:01

           PPC = 100.0%, Size = 131 bp, GC content = 45.0%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 59.5 (°C)
           RP: 3'ΔG = -3.0(kcal/mol), Tm = 57.1 (°C)
           Binding sites: 13(26/26) ... 143(26/26)
         
         >>>DRB1*16:01:01_4_fp
            1                        26
         5' TGTGGAGCAATCAGAAGGTCAATGGC 3'
            ||||||||||||||||||||||||||                                              143
         5' TGTGGAGCAATCAGAAGGTCAATGGCatttaagag...taaattccaGGGAGTGGAAGAGGATACATAGGGAG 3'
            13                                             ||||||||||||||||||||||||||
                                                        3' GGGAGTGGAAGAGGATACATAGGGAG 5'
                                                           26                       1
                                                                    DRB1*16:01:01_4_rp<<<
         

         >8_DRB1*16:01:01_4_fp_DRB1*16:01:01_4_rp_T_1_DRB1*16:01:01 
         TGTGGAGCAATCAGAAGGTCAATGGCatttaagagactcatggtgaggctagggcttcaggtatttatgttggagg
         catcaatacgtgtagtgtgttaaattccaGGGAGTGGAAGAGGATACATAGGGAG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    