MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DRB1*01:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [155]                  [60.1/59.6]         2.4783 ± 0 
2              [155]                  [60.1/58.6]         2.4831 ± 0 
3              [157]                  [60.1/58.6]         2.4866 ± 0 
4              [157]                  [60.1/57.6]         2.5523 ± 0 
5              [158]                  [60.1/60.5]         2.5844 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 2.4783 ± 0, Mean Tm: 59.9 ± 0.3 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DRB1*01:01:01_0    2.4783        155       60.1 / 59.6    5'-TGGCCTCCCAAAGTGCTGGGAT-3' / 5'-TGGAGAATTCCCTGCTGTGCTCCT-3'


* Template 1: DRB1*01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*01:01:01_0_fp + DRB1*01:01:01_0_rp ==> T1: DRB1*01:01:01

           PPC = 93.9%, Size = 155 bp, GC content = 47.1%
           FP: 3'ΔG = -2.5(kcal/mol), Tm = 60.1 (°C)
           RP: 3'ΔG = -2.4(kcal/mol), Tm = 59.6 (°C)
           Binding sites: 2(22/22) ... 156(24/24)
         
         >>>DRB1*01:01:01_0_fp
            1                    22
         5' TGGCCTCCCAAAGTGCTGGGAT 3'
            ||||||||||||||||||||||                                                  156
         5' TGGCCTCCCAAAGTGCTGGGATtataggcgtgag...ggaagactatttAGGAGCACAGCAGGGAATTCTCCA 3'
            2                                                ||||||||||||||||||||||||
                                                          3' AGGAGCACAGCAGGGAATTCTCCA 5'
                                                             24                     1
                                                                    DRB1*01:01:01_0_rp<<<
         

         >16_DRB1*01:01:01_0_fp_DRB1*01:01:01_0_rp_T_1_DRB1*01:01:01 
         TGGCCTCCCAAAGTGCTGGGATtataggcgtgagccactgcacccggcctatattcaatttttaaaactaattcta
         gctactctgtggggattggattgttggggttcaccagtggttaggaagactatttAGGAGCACAGCAGGGAATTCT
         CCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 2.4831 ± 0, Mean Tm: 59.4 ± 1.0 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DRB1*01:01:01_1    2.4831        155       60.1 / 58.6    5'-TGGCCTCCCAAAGTGCTGGGAT-3' / 5'-TGGAGAATTCCCTGCTGTGCTCC-3'


* Template 1: DRB1*01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*01:01:01_1_fp + DRB1*01:01:01_1_rp ==> T1: DRB1*01:01:01

           PPC = 96.9%, Size = 155 bp, GC content = 47.1%
           FP: 3'ΔG = -2.5(kcal/mol), Tm = 60.1 (°C)
           RP: 3'ΔG = -3.4(kcal/mol), Tm = 58.6 (°C)
           Binding sites: 2(22/22) ... 156(23/23)
         
         >>>DRB1*01:01:01_1_fp
            1                    22
         5' TGGCCTCCCAAAGTGCTGGGAT 3'
            ||||||||||||||||||||||                                                   156
         5' TGGCCTCCCAAAGTGCTGGGATtataggcgtgagc...ggaagactatttaGGAGCACAGCAGGGAATTCTCCA 3'
            2                                                  |||||||||||||||||||||||
                                                            3' GGAGCACAGCAGGGAATTCTCCA 5'
                                                               23                    1
                                                                    DRB1*01:01:01_1_rp<<<
         

         >7_DRB1*01:01:01_1_fp_DRB1*01:01:01_1_rp_T_1_DRB1*01:01:01 
         TGGCCTCCCAAAGTGCTGGGATtataggcgtgagccactgcacccggcctatattcaatttttaaaactaattcta
         gctactctgtggggattggattgttggggttcaccagtggttaggaagactatttaGGAGCACAGCAGGGAATTCT
         CCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 2.4866 ± 0, Mean Tm: 59.4 ± 1.1 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DRB1*01:01:01_2    2.4866        157       60.1 / 58.6    5'-TGGCCTCCCAAAGTGCTGGGAT-3' / 5'-CCTGGAGAATTCCCTGCTGTGCT-3'


* Template 1: DRB1*01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*01:01:01_2_fp + DRB1*01:01:01_2_rp ==> T1: DRB1*01:01:01

           PPC = 96.9%, Size = 157 bp, GC content = 47.8%
           FP: 3'ΔG = -2.5(kcal/mol), Tm = 60.1 (°C)
           RP: 3'ΔG = -3.1(kcal/mol), Tm = 58.6 (°C)
           Binding sites: 2(22/22) ... 158(23/23)
         
         >>>DRB1*01:01:01_2_fp
            1                    22
         5' TGGCCTCCCAAAGTGCTGGGAT 3'
            ||||||||||||||||||||||                                                   158
         5' TGGCCTCCCAAAGTGCTGGGATtataggcgtgagc...aagactatttaggAGCACAGCAGGGAATTCTCCAGG 3'
            2                                                  |||||||||||||||||||||||
                                                            3' AGCACAGCAGGGAATTCTCCAGG 5'
                                                               23                    1
                                                                    DRB1*01:01:01_2_rp<<<
         

         >13_DRB1*01:01:01_2_fp_DRB1*01:01:01_2_rp_T_1_DRB1*01:01:01 
         TGGCCTCCCAAAGTGCTGGGATtataggcgtgagccactgcacccggcctatattcaatttttaaaactaattcta
         gctactctgtggggattggattgttggggttcaccagtggttaggaagactatttaggAGCACAGCAGGGAATTCT
         CCAGG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 2.5523 ± 0, Mean Tm: 58.8 ± 1.8 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*01:01:01_3    2.5523        157       60.1 / 57.6    5'-TGGCCTCCCAAAGTGCTGGGAT-3' / 5'-CCTGGAGAATTCCCTGCTGTGC-3'


* Template 1: DRB1*01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*01:01:01_3_fp + DRB1*01:01:01_3_rp ==> T1: DRB1*01:01:01

           PPC = 100.0%, Size = 157 bp, GC content = 47.8%
           FP: 3'ΔG = -2.5(kcal/mol), Tm = 60.1 (°C)
           RP: 3'ΔG = -3.2(kcal/mol), Tm = 57.6 (°C)
           Binding sites: 2(22/22) ... 158(22/22)
         
         >>>DRB1*01:01:01_3_fp
            1                    22
         5' TGGCCTCCCAAAGTGCTGGGAT 3'
            ||||||||||||||||||||||                                                  158
         5' TGGCCTCCCAAAGTGCTGGGATtataggcgtgagc...agactatttaggaGCACAGCAGGGAATTCTCCAGG 3'
            2                                                  ||||||||||||||||||||||
                                                            3' GCACAGCAGGGAATTCTCCAGG 5'
                                                               22                   1
                                                                    DRB1*01:01:01_3_rp<<<
         

         >4_DRB1*01:01:01_3_fp_DRB1*01:01:01_3_rp_T_1_DRB1*01:01:01 
         TGGCCTCCCAAAGTGCTGGGATtataggcgtgagccactgcacccggcctatattcaatttttaaaactaattcta
         gctactctgtggggattggattgttggggttcaccagtggttaggaagactatttaggaGCACAGCAGGGAATTCT
         CCAGG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 2.5844 ± 0, Mean Tm: 60.3 ± 0.3 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DRB1*01:01:01_4    2.5844        158       60.1 / 60.5    5'-TGGCCTCCCAAAGTGCTGGGAT-3' / 5'-CCCTGGAGAATTCCCTGCTGTGCT-3'


* Template 1: DRB1*01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*01:01:01_4_fp + DRB1*01:01:01_4_rp ==> T1: DRB1*01:01:01

           PPC = 93.9%, Size = 158 bp, GC content = 48.1%
           FP: 3'ΔG = -2.5(kcal/mol), Tm = 60.1 (°C)
           RP: 3'ΔG = -3.1(kcal/mol), Tm = 60.5 (°C)
           Binding sites: 2(22/22) ... 159(24/24)
         
         >>>DRB1*01:01:01_4_fp
            1                    22
         5' TGGCCTCCCAAAGTGCTGGGAT 3'
            ||||||||||||||||||||||                                                  159
         5' TGGCCTCCCAAAGTGCTGGGATtataggcgtgag...agactatttaggAGCACAGCAGGGAATTCTCCAGGG 3'
            2                                                ||||||||||||||||||||||||
                                                          3' AGCACAGCAGGGAATTCTCCAGGG 5'
                                                             24                     1
                                                                    DRB1*01:01:01_4_rp<<<
         

         >25_DRB1*01:01:01_4_fp_DRB1*01:01:01_4_rp_T_1_DRB1*01:01:01 
         TGGCCTCCCAAAGTGCTGGGATtataggcgtgagccactgcacccggcctatattcaatttttaaaactaattcta
         gctactctgtggggattggattgttggggttcaccagtggttaggaagactatttaggAGCACAGCAGGGAATTCT
         CCAGGG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    