MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DRB1-01region

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [130]                  [59.0/60.0]         3.0011 ± 0 
2              [133]                  [59.9/60.0]         3.0653 ± 0 
3              [131]                  [60.2/60.0]         3.1862 ± 0 
4              [134]                  [58.8/60.0]         3.2270 ± 0 
5              [135]                  [59.7/60.0]         3.2889 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 3.0011 ± 0, Mean Tm: 59.5 ± 0.7 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DRB1-01region_0    3.0011        130       59.0 / 60.0    5'-GTCAGTGTCTTCTCAGGAGGCTGC-3' / 5'-ATCTTTCCAGCAACCGCACCCG-3'


* Template 1: DRB1-01region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-01region_0_fp + DRB1-01region_0_rp ==> T1: DRB1-01region

           PPC = 93.9%, Size = 130 bp, GC content = 53.8%
           FP: 3'ΔG = -3.9(kcal/mol), Tm = 59.0 (°C)
           RP: 3'ΔG = -3.9(kcal/mol), Tm = 60.0 (°C)
           Binding sites: 6(24/24) ... 135(22/22)
         
         >>>DRB1-01region_0_fp
            1                      24
         5' GTCAGTGTCTTCTCAGGAGGCTGC 3'
            ||||||||||||||||||||||||                                                135
         5' GTCAGTGTCTTCTCAGGAGGCTGCccgtgtgaccgg...aatgggacggagCGGGTGCGGTTGCTGGAAAGAT 3'
            6                                                  ||||||||||||||||||||||
                                                            3' CGGGTGCGGTTGCTGGAAAGAT 5'
                                                               22                   1
                                                                    DRB1-01region_0_rp<<<
         

         >1_DRB1-01region_0_fp_DRB1-01region_0_rp_T_1_DRB1-01region 
         GTCAGTGTCTTCTCAGGAGGCTGCccgtgtgaccggatccttcgtgtccccacagcacgtttcttgtggcagctta
         agtttgaatgtcatttcttcaatgggacggagCGGGTGCGGTTGCTGGAAAGAT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 3.0653 ± 0, Mean Tm: 60.0 ± 0.0 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                     

T1: DRB1-01region_1    3.0653        133       59.9 / 60.0    5'-GCTGTCAGTGTCTTCTCAGGAGGCT-3' / 5'-ATCTTTCCAGCAACCGCACCCG-3'


* Template 1: DRB1-01region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-01region_1_fp + DRB1-01region_1_rp ==> T1: DRB1-01region

           PPC = 91.0%, Size = 133 bp, GC content = 54.1%
           FP: 3'ΔG = -3.2(kcal/mol), Tm = 59.9 (°C)
           RP: 3'ΔG = -3.9(kcal/mol), Tm = 60.0 (°C)
           Binding sites: 3(25/25) ... 135(22/22)
         
         >>>DRB1-01region_1_fp
            1                       25
         5' GCTGTCAGTGTCTTCTCAGGAGGCT 3'
            |||||||||||||||||||||||||                                                135
         5' GCTGTCAGTGTCTTCTCAGGAGGCTgcccgtgtgacc...aatgggacggagCGGGTGCGGTTGCTGGAAAGAT 3'
            3                                                   ||||||||||||||||||||||
                                                             3' CGGGTGCGGTTGCTGGAAAGAT 5'
                                                                22                   1
                                                                    DRB1-01region_1_rp<<<
         

         >17_DRB1-01region_1_fp_DRB1-01region_1_rp_T_1_DRB1-01region 
         GCTGTCAGTGTCTTCTCAGGAGGCTgcccgtgtgaccggatccttcgtgtccccacagcacgtttcttgtggcagc
         ttaagtttgaatgtcatttcttcaatgggacggagCGGGTGCGGTTGCTGGAAAGAT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 3.1862 ± 0, Mean Tm: 60.1 ± 0.1 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                     

T1: DRB1-01region_2    3.1862        131       60.2 / 60.0    5'-TGTCAGTGTCTTCTCAGGAGGCTGC-3' / 5'-ATCTTTCCAGCAACCGCACCCG-3'


* Template 1: DRB1-01region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-01region_2_fp + DRB1-01region_2_rp ==> T1: DRB1-01region

           PPC = 91.0%, Size = 131 bp, GC content = 53.4%
           FP: 3'ΔG = -3.9(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -3.9(kcal/mol), Tm = 60.0 (°C)
           Binding sites: 5(25/25) ... 135(22/22)
         
         >>>DRB1-01region_2_fp
            1                       25
         5' TGTCAGTGTCTTCTCAGGAGGCTGC 3'
            |||||||||||||||||||||||||                                                135
         5' TGTCAGTGTCTTCTCAGGAGGCTGCccgtgtgaccgg...aatgggacggagCGGGTGCGGTTGCTGGAAAGAT 3'
            5                                                   ||||||||||||||||||||||
                                                             3' CGGGTGCGGTTGCTGGAAAGAT 5'
                                                                22                   1
                                                                    DRB1-01region_2_rp<<<
         

         >13_DRB1-01region_2_fp_DRB1-01region_2_rp_T_1_DRB1-01region 
         TGTCAGTGTCTTCTCAGGAGGCTGCccgtgtgaccggatccttcgtgtccccacagcacgtttcttgtggcagctt
         aagtttgaatgtcatttcttcaatgggacggagCGGGTGCGGTTGCTGGAAAGAT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 3.2270 ± 0, Mean Tm: 59.4 ± 0.9 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DRB1-01region_3    3.227         134       58.8 / 60.0    5'-CGCTGTCAGTGTCTTCTCAGGAGG-3' / 5'-ATCTTTCCAGCAACCGCACCCG-3'


* Template 1: DRB1-01region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-01region_3_fp + DRB1-01region_3_rp ==> T1: DRB1-01region

           PPC = 93.9%, Size = 134 bp, GC content = 54.5%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 58.8 (°C)
           RP: 3'ΔG = -3.9(kcal/mol), Tm = 60.0 (°C)
           Binding sites: 2(24/24) ... 135(22/22)
         
         >>>DRB1-01region_3_fp
            1                      24
         5' CGCTGTCAGTGTCTTCTCAGGAGG 3'
            ||||||||||||||||||||||||                                                135
         5' CGCTGTCAGTGTCTTCTCAGGAGGctgcccgtgtga...aatgggacggagCGGGTGCGGTTGCTGGAAAGAT 3'
            2                                                  ||||||||||||||||||||||
                                                            3' CGGGTGCGGTTGCTGGAAAGAT 5'
                                                               22                   1
                                                                    DRB1-01region_3_rp<<<
         

         >9_DRB1-01region_3_fp_DRB1-01region_3_rp_T_1_DRB1-01region 
         CGCTGTCAGTGTCTTCTCAGGAGGctgcccgtgtgaccggatccttcgtgtccccacagcacgtttcttgtggcag
         cttaagtttgaatgtcatttcttcaatgggacggagCGGGTGCGGTTGCTGGAAAGAT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 3.2889 ± 0, Mean Tm: 59.9 ± 0.2 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                     

T1: DRB1-01region_4    3.2889        135       59.7 / 60.0    5'-TCGCTGTCAGTGTCTTCTCAGGAGG-3' / 5'-ATCTTTCCAGCAACCGCACCCG-3'


* Template 1: DRB1-01region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-01region_4_fp + DRB1-01region_4_rp ==> T1: DRB1-01region

           PPC = 91.0%, Size = 135 bp, GC content = 54.1%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 59.7 (°C)
           RP: 3'ΔG = -3.9(kcal/mol), Tm = 60.0 (°C)
           Binding sites: 1(25/25) ... 135(22/22)
         
         >>>DRB1-01region_4_fp
            1                       25
         5' TCGCTGTCAGTGTCTTCTCAGGAGG 3'
            |||||||||||||||||||||||||                                                135
         5' TCGCTGTCAGTGTCTTCTCAGGAGGctgcccgtgtga...aatgggacggagCGGGTGCGGTTGCTGGAAAGAT 3'
            1                                                   ||||||||||||||||||||||
                                                             3' CGGGTGCGGTTGCTGGAAAGAT 5'
                                                                22                   1
                                                                    DRB1-01region_4_rp<<<
         

         >25_DRB1-01region_4_fp_DRB1-01region_4_rp_T_1_DRB1-01region 
         TCGCTGTCAGTGTCTTCTCAGGAGGctgcccgtgtgaccggatccttcgtgtccccacagcacgtttcttgtggca
         gcttaagtttgaatgtcatttcttcaatgggacggagCGGGTGCGGTTGCTGGAAAGAT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    