MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: A*01:01:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [130]                  [60.4/59.6]         0.8336 ± 0 
2              [130]                  [60.7/59.9]         0.8883 ± 0 
3              [130]                  [60.4/59.2]         1.1929 ± 0 
4              [130]                  [59.9/60.2]         1.3249 ± 0 
5              [131]                  [61.3/59.9]         1.4472 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 0.8336 ± 0, Mean Tm: 60.0 ± 0.6 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: A*01:01:01:01_0    0.8336        130       60.4 / 59.6    5'-CCGTGGATAGAGCAGGAGGGGC-3' / 5'-ACTCACCGTCCTCGCTCTGGTT-3'


* Template 1: A*01:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** A*01:01:01:01_0_fp + A*01:01:01:01_0_rp ==> T1: A*01:01:01:01

           PPC = 100.0%, Size = 130 bp, GC content = 61.5%
           FP: 3'ΔG = -4.4(kcal/mol), Tm = 60.4 (°C)
           RP: 3'ΔG = -2.3(kcal/mol), Tm = 59.6 (°C)
           Binding sites: 11(22/22) ... 140(22/22)
         
         >>>A*01:01:01:01_0_fp
            1                    22
         5' CCGTGGATAGAGCAGGAGGGGC 3'
            ||||||||||||||||||||||                                                  140
         5' CCGTGGATAGAGCAGGAGGGGCcggagtattggga...gcgcggctactacAACCAGAGCGAGGACGGTGAGT 3'
            11                                                 ||||||||||||||||||||||
                                                            3' AACCAGAGCGAGGACGGTGAGT 5'
                                                               22                   1
                                                                    A*01:01:01:01_0_rp<<<
         

         >10_A*01:01:01:01_0_fp_A*01:01:01:01_0_rp_T_1_A*01:01:01:01 
         CCGTGGATAGAGCAGGAGGGGCcggagtattgggaccaggagacacggaatatgaaggcccactcacagactgacc
         gagcgaacctggggaccctgcgcggctactacAACCAGAGCGAGGACGGTGAGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 0.8883 ± 0, Mean Tm: 60.3 ± 0.6 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: A*01:01:01:01_1    0.8883        130       60.7 / 59.9    5'-CGCCGTGGATAGAGCAGGAGGG-3' / 5'-TCACCGTCCTCGCTCTGGTTGT-3'


* Template 1: A*01:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** A*01:01:01:01_1_fp + A*01:01:01:01_1_rp ==> T1: A*01:01:01:01

           PPC = 100.0%, Size = 130 bp, GC content = 62.3%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 60.7 (°C)
           RP: 3'ΔG = -2.0(kcal/mol), Tm = 59.9 (°C)
           Binding sites: 9(22/22) ... 138(22/22)
         
         >>>A*01:01:01:01_1_fp
            1                    22
         5' CGCCGTGGATAGAGCAGGAGGG 3'
            ||||||||||||||||||||||                                                  138
         5' CGCCGTGGATAGAGCAGGAGGGgccggagtattgg...ctgcgcggctactACAACCAGAGCGAGGACGGTGA 3'
            9                                                  ||||||||||||||||||||||
                                                            3' ACAACCAGAGCGAGGACGGTGA 5'
                                                               22                   1
                                                                    A*01:01:01:01_1_rp<<<
         

         >11_A*01:01:01:01_1_fp_A*01:01:01:01_1_rp_T_1_A*01:01:01:01 
         CGCCGTGGATAGAGCAGGAGGGgccggagtattgggaccaggagacacggaatatgaaggcccactcacagactga
         ccgagcgaacctggggaccctgcgcggctactACAACCAGAGCGAGGACGGTGA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 1.1929 ± 0, Mean Tm: 59.8 ± 0.8 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: A*01:01:01:01_2    1.1929        130       60.4 / 59.2    5'-GCCGTGGATAGAGCAGGAGGGG-3' / 5'-CTCACCGTCCTCGCTCTGGTTG-3'


* Template 1: A*01:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** A*01:01:01:01_2_fp + A*01:01:01:01_2_rp ==> T1: A*01:01:01:01

           PPC = 100.0%, Size = 130 bp, GC content = 62.3%
           FP: 3'ΔG = -3.4(kcal/mol), Tm = 60.4 (°C)
           RP: 3'ΔG = -2.5(kcal/mol), Tm = 59.2 (°C)
           Binding sites: 10(22/22) ... 139(22/22)
         
         >>>A*01:01:01:01_2_fp
            1                    22
         5' GCCGTGGATAGAGCAGGAGGGG 3'
            ||||||||||||||||||||||                                                  139
         5' GCCGTGGATAGAGCAGGAGGGGccggagtattggg...tgcgcggctactaCAACCAGAGCGAGGACGGTGAG 3'
            10                                                 ||||||||||||||||||||||
                                                            3' CAACCAGAGCGAGGACGGTGAG 5'
                                                               22                   1
                                                                    A*01:01:01:01_2_rp<<<
         

         >13_A*01:01:01:01_2_fp_A*01:01:01:01_2_rp_T_1_A*01:01:01:01 
         GCCGTGGATAGAGCAGGAGGGGccggagtattgggaccaggagacacggaatatgaaggcccactcacagactgac
         cgagcgaacctggggaccctgcgcggctactaCAACCAGAGCGAGGACGGTGAG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 1.3249 ± 0, Mean Tm: 60.1 ± 0.2 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                 

T1: A*01:01:01:01_3    1.3249        130       59.9 / 60.2    5'-GATAGAGCAGGAGGGGCCGGAG-3' / 5'-GGGTCACTCACCGTCCTCGCT-3'


* Template 1: A*01:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** A*01:01:01:01_3_fp + A*01:01:01:01_3_rp ==> T1: A*01:01:01:01

           PPC = 96.7%, Size = 130 bp, GC content = 61.5%
           FP: 3'ΔG = -3.3(kcal/mol), Tm = 59.9 (°C)
           RP: 3'ΔG = -3.6(kcal/mol), Tm = 60.2 (°C)
           Binding sites: 16(22/22) ... 145(21/21)
         
         >>>A*01:01:01:01_3_fp
            1                    22
         5' GATAGAGCAGGAGGGGCCGGAG 3'
            ||||||||||||||||||||||                                                   145
         5' GATAGAGCAGGAGGGGCCGGAGtattgggaccagga...gctactacaaccagAGCGAGGACGGTGAGTGACCC 3'
            16                                                   |||||||||||||||||||||
                                                              3' AGCGAGGACGGTGAGTGACCC 5'
                                                                 21                  1
                                                                    A*01:01:01:01_3_rp<<<
         

         >21_A*01:01:01:01_3_fp_A*01:01:01:01_3_rp_T_1_A*01:01:01:01 
         GATAGAGCAGGAGGGGCCGGAGtattgggaccaggagacacggaatatgaaggcccactcacagactgaccgagcg
         aacctggggaccctgcgcggctactacaaccagAGCGAGGACGGTGAGTGACCC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 1.4472 ± 0, Mean Tm: 60.6 ± 1.0 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: A*01:01:01:01_4    1.4472        131       61.3 / 59.9    5'-GCGCCGTGGATAGAGCAGGAGG-3' / 5'-TCACCGTCCTCGCTCTGGTTGT-3'


* Template 1: A*01:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** A*01:01:01:01_4_fp + A*01:01:01:01_4_rp ==> T1: A*01:01:01:01

           PPC = 100.0%, Size = 131 bp, GC content = 62.6%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 61.3 (°C)
           RP: 3'ΔG = -2.0(kcal/mol), Tm = 59.9 (°C)
           Binding sites: 8(22/22) ... 138(22/22)
         
         >>>A*01:01:01:01_4_fp
            1                    22
         5' GCGCCGTGGATAGAGCAGGAGG 3'
            ||||||||||||||||||||||                                                  138
         5' GCGCCGTGGATAGAGCAGGAGGggccggagtattg...ctgcgcggctactACAACCAGAGCGAGGACGGTGA 3'
            8                                                  ||||||||||||||||||||||
                                                            3' ACAACCAGAGCGAGGACGGTGA 5'
                                                               22                   1
                                                                    A*01:01:01:01_4_rp<<<
         

         >17_A*01:01:01:01_4_fp_A*01:01:01:01_4_rp_T_1_A*01:01:01:01 
         GCGCCGTGGATAGAGCAGGAGGggccggagtattgggaccaggagacacggaatatgaaggcccactcacagactg
         accgagcgaacctggggaccctgcgcggctactACAACCAGAGCGAGGACGGTGA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    