MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: B*08:01:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [130]                  [60.4/61.7]         2.1106 ± 0 
2              [130]                  [60.4/60.8]         2.2751 ± 0 
3              [131]                  [60.7/61.7]         2.4230 ± 0 
4              [131]                  [60.4/62.1]         2.5363 ± 0 
5              [130]                  [60.4/62.1]         2.5363 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 2.1106 ± 0, Mean Tm: 61.1 ± 0.9 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: B*08:01:01:01_0    2.1106        130       60.4 / 61.7    5'-GCCGTGGATAGAGCAGGAGGGG-3' / 5'-CTCACCGGCCTCGCTCTGGTTG-3'


* Template 1: B*08:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** B*08:01:01:01_0_fp + B*08:01:01:01_0_rp ==> T1: B*08:01:01:01

           PPC = 100.0%, Size = 130 bp, GC content = 60.8%
           FP: 3'ΔG = -3.4(kcal/mol), Tm = 60.4 (°C)
           RP: 3'ΔG = -2.5(kcal/mol), Tm = 61.7 (°C)
           Binding sites: 2(22/22) ... 131(22/22)
         
         >>>B*08:01:01:01_0_fp
            1                    22
         5' GCCGTGGATAGAGCAGGAGGGG 3'
            ||||||||||||||||||||||                                                  131
         5' GCCGTGGATAGAGCAGGAGGGGccggagtattggg...tgcgcggctactaCAACCAGAGCGAGGCCGGTGAG 3'
            2                                                  ||||||||||||||||||||||
                                                            3' CAACCAGAGCGAGGCCGGTGAG 5'
                                                               22                   1
                                                                    B*08:01:01:01_0_rp<<<
         

         >3_B*08:01:01:01_0_fp_B*08:01:01:01_0_rp_T_1_B*08:01:01:01 
         GCCGTGGATAGAGCAGGAGGGGccggagtattgggaccggaacacacagatcttcaagaccaacacacagactgac
         cgagagagcctgcggaacctgcgcggctactaCAACCAGAGCGAGGCCGGTGAG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 2.2751 ± 0, Mean Tm: 60.6 ± 0.3 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                 

T1: B*08:01:01:01_1    2.2751        130       60.4 / 60.8    5'-GCCGTGGATAGAGCAGGAGGGG-3' / 5'-CTCACCGGCCTCGCTCTGGTT-3'


* Template 1: B*08:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** B*08:01:01:01_1_fp + B*08:01:01:01_1_rp ==> T1: B*08:01:01:01

           PPC = 96.7%, Size = 130 bp, GC content = 60.8%
           FP: 3'ΔG = -3.4(kcal/mol), Tm = 60.4 (°C)
           RP: 3'ΔG = -2.3(kcal/mol), Tm = 60.8 (°C)
           Binding sites: 2(22/22) ... 131(21/21)
         
         >>>B*08:01:01:01_1_fp
            1                    22
         5' GCCGTGGATAGAGCAGGAGGGG 3'
            ||||||||||||||||||||||                                                   131
         5' GCCGTGGATAGAGCAGGAGGGGccggagtattggga...tgcgcggctactacAACCAGAGCGAGGCCGGTGAG 3'
            2                                                    |||||||||||||||||||||
                                                              3' AACCAGAGCGAGGCCGGTGAG 5'
                                                                 21                  1
                                                                    B*08:01:01:01_1_rp<<<
         

         >23_B*08:01:01:01_1_fp_B*08:01:01:01_1_rp_T_1_B*08:01:01:01 
         GCCGTGGATAGAGCAGGAGGGGccggagtattgggaccggaacacacagatcttcaagaccaacacacagactgac
         cgagagagcctgcggaacctgcgcggctactacAACCAGAGCGAGGCCGGTGAG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 2.4230 ± 0, Mean Tm: 61.2 ± 0.7 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: B*08:01:01:01_2    2.423         131       60.7 / 61.7    5'-CGCCGTGGATAGAGCAGGAGGG-3' / 5'-CTCACCGGCCTCGCTCTGGTTG-3'


* Template 1: B*08:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** B*08:01:01:01_2_fp + B*08:01:01:01_2_rp ==> T1: B*08:01:01:01

           PPC = 100.0%, Size = 131 bp, GC content = 61.1%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 60.7 (°C)
           RP: 3'ΔG = -2.5(kcal/mol), Tm = 61.7 (°C)
           Binding sites: 1(22/22) ... 131(22/22)
         
         >>>B*08:01:01:01_2_fp
            1                    22
         5' CGCCGTGGATAGAGCAGGAGGG 3'
            ||||||||||||||||||||||                                                  131
         5' CGCCGTGGATAGAGCAGGAGGGgccggagtattgg...tgcgcggctactaCAACCAGAGCGAGGCCGGTGAG 3'
            1                                                  ||||||||||||||||||||||
                                                            3' CAACCAGAGCGAGGCCGGTGAG 5'
                                                               22                   1
                                                                    B*08:01:01:01_2_rp<<<
         

         >16_B*08:01:01:01_2_fp_B*08:01:01:01_2_rp_T_1_B*08:01:01:01 
         CGCCGTGGATAGAGCAGGAGGGgccggagtattgggaccggaacacacagatcttcaagaccaacacacagactga
         ccgagagagcctgcggaacctgcgcggctactaCAACCAGAGCGAGGCCGGTGAG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 2.5363 ± 0, Mean Tm: 61.3 ± 1.2 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: B*08:01:01:01_3    2.5363        131       60.4 / 62.1    5'-GCCGTGGATAGAGCAGGAGGGG-3' / 5'-ACTCACCGGCCTCGCTCTGGTT-3'


* Template 1: B*08:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** B*08:01:01:01_3_fp + B*08:01:01:01_3_rp ==> T1: B*08:01:01:01

           PPC = 100.0%, Size = 131 bp, GC content = 60.3%
           FP: 3'ΔG = -3.4(kcal/mol), Tm = 60.4 (°C)
           RP: 3'ΔG = -2.3(kcal/mol), Tm = 62.1 (°C)
           Binding sites: 2(22/22) ... 132(22/22)
         
         >>>B*08:01:01:01_3_fp
            1                    22
         5' GCCGTGGATAGAGCAGGAGGGG 3'
            ||||||||||||||||||||||                                                  132
         5' GCCGTGGATAGAGCAGGAGGGGccggagtattggg...gcgcggctactacAACCAGAGCGAGGCCGGTGAGT 3'
            2                                                  ||||||||||||||||||||||
                                                            3' AACCAGAGCGAGGCCGGTGAGT 5'
                                                               22                   1
                                                                    B*08:01:01:01_3_rp<<<
         

         >17_B*08:01:01:01_3_fp_B*08:01:01:01_3_rp_T_1_B*08:01:01:01 
         GCCGTGGATAGAGCAGGAGGGGccggagtattgggaccggaacacacagatcttcaagaccaacacacagactgac
         cgagagagcctgcggaacctgcgcggctactacAACCAGAGCGAGGCCGGTGAGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 2.5363 ± 0, Mean Tm: 61.3 ± 1.2 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: B*08:01:01:01_4    2.5363        130       60.4 / 62.1    5'-CCGTGGATAGAGCAGGAGGGGC-3' / 5'-ACTCACCGGCCTCGCTCTGGTT-3'


* Template 1: B*08:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** B*08:01:01:01_4_fp + B*08:01:01:01_4_rp ==> T1: B*08:01:01:01

           PPC = 100.0%, Size = 130 bp, GC content = 60.0%
           FP: 3'ΔG = -4.4(kcal/mol), Tm = 60.4 (°C)
           RP: 3'ΔG = -2.3(kcal/mol), Tm = 62.1 (°C)
           Binding sites: 3(22/22) ... 132(22/22)
         
         >>>B*08:01:01:01_4_fp
            1                    22
         5' CCGTGGATAGAGCAGGAGGGGC 3'
            ||||||||||||||||||||||                                                  132
         5' CCGTGGATAGAGCAGGAGGGGCcggagtattggga...gcgcggctactacAACCAGAGCGAGGCCGGTGAGT 3'
            3                                                  ||||||||||||||||||||||
                                                            3' AACCAGAGCGAGGCCGGTGAGT 5'
                                                               22                   1
                                                                    B*08:01:01:01_4_rp<<<
         

         >10_B*08:01:01:01_4_fp_B*08:01:01:01_4_rp_T_1_B*08:01:01:01 
         CCGTGGATAGAGCAGGAGGGGCcggagtattgggaccggaacacacagatcttcaagaccaacacacagactgacc
         gagagagcctgcggaacctgcgcggctactacAACCAGAGCGAGGCCGGTGAGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    