MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: C*01:02:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [130]                  [60.2/60.8]         4.0881 ± 0 
2              [132]                  [60.2/61.2]         4.4708 ± 0 
3              [133]                  [60.2/61.5]         4.7390 ± 0 
4              [134]                  [60.2/61.5]         4.7390 ± 0 
5              [131]                  [60.2/61.5]         4.7390 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 4.0881 ± 0, Mean Tm: 60.5 ± 0.4 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)               

T1: C*01:02:01:01_0    4.0881        130       60.2 / 60.8    5'-CCGAGATGCGGGTCATGGCG-3' / 5'-GGCACCTCGTTCCTCTCCGCA-3'


* Template 1: C*01:02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** C*01:02:01:01_0_fp + C*01:02:01:01_0_rp ==> T1: C*01:02:01:01

           PPC = 96.6%, Size = 130 bp, GC content = 69.2%
           FP: 3'ΔG = -4.3(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -4.3(kcal/mol), Tm = 60.8 (°C)
           Binding sites: 2(20/20) ... 131(21/21)
         
         >>>C*01:02:01:01_0_fp
            1                  20
         5' CCGAGATGCGGGTCATGGCG 3'
            ||||||||||||||||||||                                                     131
         5' CCGAGATGCGGGTCATGGCGccccgaaccctcatc...gagggaaacggcctcTGCGGAGAGGAACGAGGTGCC 3'
            2                                                    |||||||||||||||||||||
                                                              3' TGCGGAGAGGAACGAGGTGCC 5'
                                                                 21                  1
                                                                    C*01:02:01:01_0_rp<<<
         

         >1_C*01:02:01:01_0_fp_C*01:02:01:01_0_rp_T_1_C*01:02:01:01 
         CCGAGATGCGGGTCATGGCGccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggc
         ctgtgagtgcggggttgggagggaaacggcctcTGCGGAGAGGAACGAGGTGCC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 4.4708 ± 0, Mean Tm: 60.7 ± 0.7 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)               

T1: C*01:02:01:01_1    4.4708        132       60.2 / 61.2    5'-CCGAGATGCGGGTCATGGCG-3' / 5'-CGGGCACCTCGTTCCTCTCCG-3'


* Template 1: C*01:02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** C*01:02:01:01_1_fp + C*01:02:01:01_1_rp ==> T1: C*01:02:01:01

           PPC = 96.6%, Size = 132 bp, GC content = 69.7%
           FP: 3'ΔG = -4.3(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -3.3(kcal/mol), Tm = 61.2 (°C)
           Binding sites: 2(20/20) ... 133(21/21)
         
         >>>C*01:02:01:01_1_fp
            1                  20
         5' CCGAGATGCGGGTCATGGCG 3'
            ||||||||||||||||||||                                                     133
         5' CCGAGATGCGGGTCATGGCGccccgaaccctcatc...gggaaacggcctctgCGGAGAGGAACGAGGTGCCCG 3'
            2                                                    |||||||||||||||||||||
                                                              3' CGGAGAGGAACGAGGTGCCCG 5'
                                                                 21                  1
                                                                    C*01:02:01:01_1_rp<<<
         

         >12_C*01:02:01:01_1_fp_C*01:02:01:01_1_rp_T_1_C*01:02:01:01 
         CCGAGATGCGGGTCATGGCGccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggc
         ctgtgagtgcggggttgggagggaaacggcctctgCGGAGAGGAACGAGGTGCCCG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 4.7390 ± 0, Mean Tm: 60.9 ± 0.9 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)               

T1: C*01:02:01:01_2    4.739         133       60.2 / 61.5    5'-CCGAGATGCGGGTCATGGCG-3' / 5'-GCGGGCACCTCGTTCCTCTCC-3'


* Template 1: C*01:02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** C*01:02:01:01_2_fp + C*01:02:01:01_2_rp ==> T1: C*01:02:01:01

           PPC = 96.6%, Size = 133 bp, GC content = 69.9%
           FP: 3'ΔG = -4.3(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -2.4(kcal/mol), Tm = 61.5 (°C)
           Binding sites: 2(20/20) ... 134(21/21)
         
         >>>C*01:02:01:01_2_fp
            1                  20
         5' CCGAGATGCGGGTCATGGCG 3'
            ||||||||||||||||||||                                                     134
         5' CCGAGATGCGGGTCATGGCGccccgaaccctcatc...ggaaacggcctctgcGGAGAGGAACGAGGTGCCCGC 3'
            2                                                    |||||||||||||||||||||
                                                              3' GGAGAGGAACGAGGTGCCCGC 5'
                                                                 21                  1
                                                                    C*01:02:01:01_2_rp<<<
         

         >18_C*01:02:01:01_2_fp_C*01:02:01:01_2_rp_T_1_C*01:02:01:01 
         CCGAGATGCGGGTCATGGCGccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggc
         ctgtgagtgcggggttgggagggaaacggcctctgcGGAGAGGAACGAGGTGCCCGC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 4.7390 ± 0, Mean Tm: 60.9 ± 0.9 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)               

T1: C*01:02:01:01_3    4.739         134       60.2 / 61.5    5'-CCGAGATGCGGGTCATGGCG-3' / 5'-GGCGGGCACCTCGTTCCTCTC-3'


* Template 1: C*01:02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** C*01:02:01:01_3_fp + C*01:02:01:01_3_rp ==> T1: C*01:02:01:01

           PPC = 96.6%, Size = 134 bp, GC content = 70.1%
           FP: 3'ΔG = -4.3(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -1.9(kcal/mol), Tm = 61.5 (°C)
           Binding sites: 2(20/20) ... 135(21/21)
         
         >>>C*01:02:01:01_3_fp
            1                  20
         5' CCGAGATGCGGGTCATGGCG 3'
            ||||||||||||||||||||                                                     135
         5' CCGAGATGCGGGTCATGGCGccccgaaccctcatc...gaaacggcctctgcgGAGAGGAACGAGGTGCCCGCC 3'
            2                                                    |||||||||||||||||||||
                                                              3' GAGAGGAACGAGGTGCCCGCC 5'
                                                                 21                  1
                                                                    C*01:02:01:01_3_rp<<<
         

         >24_C*01:02:01:01_3_fp_C*01:02:01:01_3_rp_T_1_C*01:02:01:01 
         CCGAGATGCGGGTCATGGCGccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggc
         ctgtgagtgcggggttgggagggaaacggcctctgcgGAGAGGAACGAGGTGCCCGCC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 4.7390 ± 0, Mean Tm: 60.9 ± 0.9 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)               

T1: C*01:02:01:01_4    4.739         131       60.2 / 61.5    5'-CCGAGATGCGGGTCATGGCG-3' / 5'-GGGCACCTCGTTCCTCTCCGC-3'


* Template 1: C*01:02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** C*01:02:01:01_4_fp + C*01:02:01:01_4_rp ==> T1: C*01:02:01:01

           PPC = 96.6%, Size = 131 bp, GC content = 69.5%
           FP: 3'ΔG = -4.3(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -4.2(kcal/mol), Tm = 61.5 (°C)
           Binding sites: 2(20/20) ... 132(21/21)
         
         >>>C*01:02:01:01_4_fp
            1                  20
         5' CCGAGATGCGGGTCATGGCG 3'
            ||||||||||||||||||||                                                     132
         5' CCGAGATGCGGGTCATGGCGccccgaaccctcatc...agggaaacggcctctGCGGAGAGGAACGAGGTGCCC 3'
            2                                                    |||||||||||||||||||||
                                                              3' GCGGAGAGGAACGAGGTGCCC 5'
                                                                 21                  1
                                                                    C*01:02:01:01_4_rp<<<
         

         >10_C*01:02:01:01_4_fp_C*01:02:01:01_4_rp_T_1_C*01:02:01:01 
         CCGAGATGCGGGTCATGGCGccccgaaccctcatcctgctgctctcgggagccctggccctgaccgagacctgggc
         ctgtgagtgcggggttgggagggaaacggcctctGCGGAGAGGAACGAGGTGCCC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    