MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DPA1*02:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [103]                  [58.3/55.4]         12.2497 ± 0
2              [102]                  [57.3/55.4]         12.3019 ± 0
3              [101]                  [56.2/55.4]         12.4042 ± 0
4              [103]                  [56.2/55.4]         12.4162 ± 0
5              [103]                  [57.0/55.4]         12.5623 ± 0



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 12.2497 ± 0, Mean Tm: 56.9 ± 2.1 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                        

T1: DPA1*02:01_0    12.2497       103       58.3 / 55.4    5'-AGTCTATGTTCCCTCTGGCCCTCA-3' / 5'-AGATTCCTGTGAGATGTAAATGGGGA-3'


* Template 1: DPA1*02:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*02:01_0_fp + DPA1*02:01_0_rp ==> T1: DPA1*02:01

           PPC = 94.3%, Size = 103 bp, GC content = 39.8%
           FP: 3'ΔG = -2.5(kcal/mol), Tm = 58.3 (°C)
           RP: 3'ΔG = -3.4(kcal/mol), Tm = 55.4 (°C)
           Binding sites: 21(24/24) ... 123(26/26)
         
         >>>DPA1*02:01_0_fp
            1                      24
         5' AGTCTATGTTCCCTCTGGCCCTCA 3'
            ||||||||||||||||||||||||                                                123
         5' AGTCTATGTTCCCTCTGGCCCTCAtaataataac...atagtttcttTCCCCATTTACATCTCACAGGAATCT 3'
            21                                             ||||||||||||||||||||||||||
                                                        3' TCCCCATTTACATCTCACAGGAATCT 5'
                                                           26                       1
                                                                       DPA1*02:01_0_rp<<<
         

         >1_DPA1*02:01_0_fp_DPA1*02:01_0_rp_T_1_DPA1*02:01 
         AGTCTATGTTCCCTCTGGCCCTCAtaataataacagcaataacagccagaatttatgagactcctgcatagtttct
         tTCCCCATTTACATCTCACAGGAATCT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 12.3019 ± 0, Mean Tm: 56.3 ± 1.3 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                       

T1: DPA1*02:01_1    12.3019       102       57.3 / 55.4    5'-GTCTATGTTCCCTCTGGCCCTCA-3' / 5'-AGATTCCTGTGAGATGTAAATGGGGA-3'


* Template 1: DPA1*02:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*02:01_1_fp + DPA1*02:01_1_rp ==> T1: DPA1*02:01

           PPC = 91.3%, Size = 102 bp, GC content = 40.2%
           FP: 3'ΔG = -2.5(kcal/mol), Tm = 57.3 (°C)
           RP: 3'ΔG = -3.4(kcal/mol), Tm = 55.4 (°C)
           Binding sites: 22(23/23) ... 123(26/26)
         
         >>>DPA1*02:01_1_fp
            1                     23
         5' GTCTATGTTCCCTCTGGCCCTCA 3'
            |||||||||||||||||||||||                                                  123
         5' GTCTATGTTCCCTCTGGCCCTCAtaataataaca...catagtttcttTCCCCATTTACATCTCACAGGAATCT 3'
            22                                              ||||||||||||||||||||||||||
                                                         3' TCCCCATTTACATCTCACAGGAATCT 5'
                                                            26                       1
                                                                       DPA1*02:01_1_rp<<<
         

         >7_DPA1*02:01_1_fp_DPA1*02:01_1_rp_T_1_DPA1*02:01 
         GTCTATGTTCCCTCTGGCCCTCAtaataataacagcaataacagccagaatttatgagactcctgcatagtttctt
         TCCCCATTTACATCTCACAGGAATCT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 12.4042 ± 0, Mean Tm: 55.8 ± 0.6 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                      

T1: DPA1*02:01_2    12.4042       101       56.2 / 55.4    5'-TCTATGTTCCCTCTGGCCCTCA-3' / 5'-AGATTCCTGTGAGATGTAAATGGGGA-3'


* Template 1: DPA1*02:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*02:01_2_fp + DPA1*02:01_2_rp ==> T1: DPA1*02:01

           PPC = 88.2%, Size = 101 bp, GC content = 39.6%
           FP: 3'ΔG = -2.5(kcal/mol), Tm = 56.2 (°C)
           RP: 3'ΔG = -3.4(kcal/mol), Tm = 55.4 (°C)
           Binding sites: 23(22/22) ... 123(26/26)
         
         >>>DPA1*02:01_2_fp
            1                    22
         5' TCTATGTTCCCTCTGGCCCTCA 3'
            ||||||||||||||||||||||                                                  123
         5' TCTATGTTCCCTCTGGCCCTCAtaataataaca...catagtttcttTCCCCATTTACATCTCACAGGAATCT 3'
            23                                             ||||||||||||||||||||||||||
                                                        3' TCCCCATTTACATCTCACAGGAATCT 5'
                                                           26                       1
                                                                       DPA1*02:01_2_rp<<<
         

         >18_DPA1*02:01_2_fp_DPA1*02:01_2_rp_T_1_DPA1*02:01 
         TCTATGTTCCCTCTGGCCCTCAtaataataacagcaataacagccagaatttatgagactcctgcatagtttcttT
         CCCCATTTACATCTCACAGGAATCT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 12.4162 ± 0, Mean Tm: 55.8 ± 0.6 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                      

T1: DPA1*02:01_3    12.4162       103       56.2 / 55.4    5'-AGTCTATGTTCCCTCTGGCCCT-3' / 5'-AGATTCCTGTGAGATGTAAATGGGGA-3'


* Template 1: DPA1*02:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*02:01_3_fp + DPA1*02:01_3_rp ==> T1: DPA1*02:01

           PPC = 88.2%, Size = 103 bp, GC content = 39.8%
           FP: 3'ΔG = -3.8(kcal/mol), Tm = 56.2 (°C)
           RP: 3'ΔG = -3.4(kcal/mol), Tm = 55.4 (°C)
           Binding sites: 21(22/22) ... 123(26/26)
         
         >>>DPA1*02:01_3_fp
            1                    22
         5' AGTCTATGTTCCCTCTGGCCCT 3'
            ||||||||||||||||||||||                                                  123
         5' AGTCTATGTTCCCTCTGGCCCTcataataataa...catagtttcttTCCCCATTTACATCTCACAGGAATCT 3'
            21                                             ||||||||||||||||||||||||||
                                                        3' TCCCCATTTACATCTCACAGGAATCT 5'
                                                           26                       1
                                                                       DPA1*02:01_3_rp<<<
         

         >24_DPA1*02:01_3_fp_DPA1*02:01_3_rp_T_1_DPA1*02:01 
         AGTCTATGTTCCCTCTGGCCCTcataataataacagcaataacagccagaatttatgagactcctgcatagtttct
         tTCCCCATTTACATCTCACAGGAATCT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 12.5623 ± 0, Mean Tm: 56.2 ± 1.2 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                       

T1: DPA1*02:01_4    12.5623       103       57.0 / 55.4    5'-AGTCTATGTTCCCTCTGGCCCTC-3' / 5'-AGATTCCTGTGAGATGTAAATGGGGA-3'


* Template 1: DPA1*02:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*02:01_4_fp + DPA1*02:01_4_rp ==> T1: DPA1*02:01

           PPC = 91.3%, Size = 103 bp, GC content = 39.8%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 57.0 (°C)
           RP: 3'ΔG = -3.4(kcal/mol), Tm = 55.4 (°C)
           Binding sites: 21(23/23) ... 123(26/26)
         
         >>>DPA1*02:01_4_fp
            1                     23
         5' AGTCTATGTTCCCTCTGGCCCTC 3'
            |||||||||||||||||||||||                                                  123
         5' AGTCTATGTTCCCTCTGGCCCTCataataataac...catagtttcttTCCCCATTTACATCTCACAGGAATCT 3'
            21                                              ||||||||||||||||||||||||||
                                                         3' TCCCCATTTACATCTCACAGGAATCT 5'
                                                            26                       1
                                                                       DPA1*02:01_4_rp<<<
         

         >15_DPA1*02:01_4_fp_DPA1*02:01_4_rp_T_1_DPA1*02:01 
         AGTCTATGTTCCCTCTGGCCCTCataataataacagcaataacagccagaatttatgagactcctgcatagtttct
         tTCCCCATTTACATCTCACAGGAATCT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    