MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DPA1*01:03:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [132]                  [60.2/59.7]         0.5144 ± 0 
2              [134]                  [60.2/60.5]         0.6722 ± 0 
3              [130]                  [60.6/60.5]         1.0513 ± 0 
4              [133]                  [59.2/59.7]         1.1234 ± 0 
5              [132]                  [60.2/59.9]         1.2473 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 0.5144 ± 0, Mean Tm: 59.9 ± 0.4 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DPA1*01:03:01:01_0    0.5144        132       60.2 / 59.7    5'-TAGACCCCACAACATGCGCCCT-3' / 5'-CGTCCTCCTGAGCACTCACCCT-3'


* Template 1: DPA1*01:03:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*01:03:01:01_0_fp + DPA1*01:03:01:01_0_rp ==> T1: DPA1*01:03:01:01

           PPC = 100.0%, Size = 132 bp, GC content = 56.1%
           FP: 3'ΔG = -3.8(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -3.0(kcal/mol), Tm = 59.7 (°C)
           Binding sites: 21(22/22) ... 152(22/22)
         
         >>>DPA1*01:03:01:01_0_fp
            1                    22
         5' TAGACCCCACAACATGCGCCCT 3'
            ||||||||||||||||||||||                                                  152
         5' TAGACCCCACAACATGCGCCCTgaagacagaatgt...gctggggccatcaAGGGTGAGTGCTCAGGAGGACG 3'
            21                                                 ||||||||||||||||||||||
                                                            3' AGGGTGAGTGCTCAGGAGGACG 5'
                                                               22                   1
                                                                 DPA1*01:03:01:01_0_rp<<<
         

         >5_DPA1*01:03:01:01_0_fp_DPA1*01:03:01:01_0_rp_T_1_DPA1*01:03:01:01 
         TAGACCCCACAACATGCGCCCTgaagacagaatgttccatatcagagctgtgatcttgagagccctctccttggct
         ttcctgctgagtctccgaggagctggggccatcaAGGGTGAGTGCTCAGGAGGACG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 0.6722 ± 0, Mean Tm: 60.3 ± 0.2 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DPA1*01:03:01:01_1    0.6722        134       60.2 / 60.5    5'-TAGACCCCACAACATGCGCCCT-3' / 5'-TGCGTCCTCCTGAGCACTCACC-3'


* Template 1: DPA1*01:03:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*01:03:01:01_1_fp + DPA1*01:03:01:01_1_rp ==> T1: DPA1*01:03:01:01

           PPC = 100.0%, Size = 134 bp, GC content = 56.0%
           FP: 3'ΔG = -3.8(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -2.7(kcal/mol), Tm = 60.5 (°C)
           Binding sites: 21(22/22) ... 154(22/22)
         
         >>>DPA1*01:03:01:01_1_fp
            1                    22
         5' TAGACCCCACAACATGCGCCCT 3'
            ||||||||||||||||||||||                                                  154
         5' TAGACCCCACAACATGCGCCCTgaagacagaatgt...tggggccatcaagGGTGAGTGCTCAGGAGGACGCA 3'
            21                                                 ||||||||||||||||||||||
                                                            3' GGTGAGTGCTCAGGAGGACGCA 5'
                                                               22                   1
                                                                 DPA1*01:03:01:01_1_rp<<<
         

         >15_DPA1*01:03:01:01_1_fp_DPA1*01:03:01:01_1_rp_T_1_DPA1*01:03:01:01 
         TAGACCCCACAACATGCGCCCTgaagacagaatgttccatatcagagctgtgatcttgagagccctctccttggct
         ttcctgctgagtctccgaggagctggggccatcaagGGTGAGTGCTCAGGAGGACGCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 1.0513 ± 0, Mean Tm: 60.5 ± 0.0 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DPA1*01:03:01:01_2    1.0513        130       60.6 / 60.5    5'-CCCCACAACATGCGCCCTGAAG-3' / 5'-TGCGTCCTCCTGAGCACTCACC-3'


* Template 1: DPA1*01:03:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*01:03:01:01_2_fp + DPA1*01:03:01:01_2_rp ==> T1: DPA1*01:03:01:01

           PPC = 100.0%, Size = 130 bp, GC content = 56.9%
           FP: 3'ΔG = -1.7(kcal/mol), Tm = 60.6 (°C)
           RP: 3'ΔG = -2.7(kcal/mol), Tm = 60.5 (°C)
           Binding sites: 25(22/22) ... 154(22/22)
         
         >>>DPA1*01:03:01:01_2_fp
            1                    22
         5' CCCCACAACATGCGCCCTGAAG 3'
            ||||||||||||||||||||||                                                  154
         5' CCCCACAACATGCGCCCTGAAGacagaatgttcca...tggggccatcaagGGTGAGTGCTCAGGAGGACGCA 3'
            25                                                 ||||||||||||||||||||||
                                                            3' GGTGAGTGCTCAGGAGGACGCA 5'
                                                               22                   1
                                                                 DPA1*01:03:01:01_2_rp<<<
         

         >4_DPA1*01:03:01:01_2_fp_DPA1*01:03:01:01_2_rp_T_1_DPA1*01:03:01:01 
         CCCCACAACATGCGCCCTGAAGacagaatgttccatatcagagctgtgatcttgagagccctctccttggctttcc
         tgctgagtctccgaggagctggggccatcaagGGTGAGTGCTCAGGAGGACGCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 1.1234 ± 0, Mean Tm: 59.4 ± 0.3 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DPA1*01:03:01:01_3    1.1234        133       59.2 / 59.7    5'-ATAGACCCCACAACATGCGCCC-3' / 5'-CGTCCTCCTGAGCACTCACCCT-3'


* Template 1: DPA1*01:03:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*01:03:01:01_3_fp + DPA1*01:03:01:01_3_rp ==> T1: DPA1*01:03:01:01

           PPC = 100.0%, Size = 133 bp, GC content = 55.6%
           FP: 3'ΔG = -4.7(kcal/mol), Tm = 59.2 (°C)
           RP: 3'ΔG = -3.0(kcal/mol), Tm = 59.7 (°C)
           Binding sites: 20(22/22) ... 152(22/22)
         
         >>>DPA1*01:03:01:01_3_fp
            1                    22
         5' ATAGACCCCACAACATGCGCCC 3'
            ||||||||||||||||||||||                                                  152
         5' ATAGACCCCACAACATGCGCCCtgaagacagaatg...gctggggccatcaAGGGTGAGTGCTCAGGAGGACG 3'
            20                                                 ||||||||||||||||||||||
                                                            3' AGGGTGAGTGCTCAGGAGGACG 5'
                                                               22                   1
                                                                 DPA1*01:03:01:01_3_rp<<<
         

         >12_DPA1*01:03:01:01_3_fp_DPA1*01:03:01:01_3_rp_T_1_DPA1*01:03:01:01 
         ATAGACCCCACAACATGCGCCCtgaagacagaatgttccatatcagagctgtgatcttgagagccctctccttggc
         tttcctgctgagtctccgaggagctggggccatcaAGGGTGAGTGCTCAGGAGGACG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 1.2473 ± 0, Mean Tm: 60.1 ± 0.2 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DPA1*01:03:01:01_4    1.2473        132       60.2 / 59.9    5'-TAGACCCCACAACATGCGCCCT-3' / 5'-CGTCCTCCTGAGCACTCACCCTT-3'


* Template 1: DPA1*01:03:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPA1*01:03:01:01_4_fp + DPA1*01:03:01:01_4_rp ==> T1: DPA1*01:03:01:01

           PPC = 96.9%, Size = 132 bp, GC content = 56.1%
           FP: 3'ΔG = -3.8(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -2.6(kcal/mol), Tm = 59.9 (°C)
           Binding sites: 21(22/22) ... 152(23/23)
         
         >>>DPA1*01:03:01:01_4_fp
            1                    22
         5' TAGACCCCACAACATGCGCCCT 3'
            ||||||||||||||||||||||                                                   152
         5' TAGACCCCACAACATGCGCCCTgaagacagaatgt...agctggggccatcAAGGGTGAGTGCTCAGGAGGACG 3'
            21                                                 |||||||||||||||||||||||
                                                            3' AAGGGTGAGTGCTCAGGAGGACG 5'
                                                               23                    1
                                                                 DPA1*01:03:01:01_4_rp<<<
         

         >24_DPA1*01:03:01:01_4_fp_DPA1*01:03:01:01_4_rp_T_1_DPA1*01:03:01:01 
         TAGACCCCACAACATGCGCCCTgaagacagaatgttccatatcagagctgtgatcttgagagccctctccttggct
         ttcctgctgagtctccgaggagctggggccatcAAGGGTGAGTGCTCAGGAGGACG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    