MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DPB1*02:01:02:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [138]                  [60.0/61.4]         1.4164 ± 0 
2              [137]                  [60.0/59.5]         1.5868 ± 0 
3              [137]                  [60.0/61.7]         1.7099 ± 0 
4              [138]                  [60.0/60.8]         1.8243 ± 0 
5              [134]                  [60.0/60.8]         1.8816 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 1.4164 ± 0, Mean Tm: 60.7 ± 0.9 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DPB1*02:01:02:01_0    1.4164        138       60.0 / 61.4    5'-GCCCCCTCCCCGCAGAGAATTA-3' / 5'-GGAACTCCCCCACGTCGCTGTC-3'


* Template 1: DPB1*02:01:02:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPB1*02:01:02:01_0_fp + DPB1*02:01:02:01_0_rp ==> T1: DPB1*02:01:02:01

           PPC = 100.0%, Size = 138 bp, GC content = 58.7%
           FP: 3'ΔG = -0.1(kcal/mol), Tm = 60.0 (°C)
           RP: 3'ΔG = -2.2(kcal/mol), Tm = 61.4 (°C)
           Binding sites: 9(22/22) ... 146(22/22)
         
         >>>DPB1*02:01:02:01_0_fp
            1                    22
         5' GCCCCCTCCCCGCAGAGAATTA 3'
            ||||||||||||||||||||||                                                  146
         5' GCCCCCTCCCCGCAGAGAATTAccttttccaggga...gttcgtgcgcttcGACAGCGACGTGGGGGAGTTCC 3'
            9                                                  ||||||||||||||||||||||
                                                            3' GACAGCGACGTGGGGGAGTTCC 5'
                                                               22                   1
                                                                 DPB1*02:01:02:01_0_rp<<<
         

         >6_DPB1*02:01:02:01_0_fp_DPB1*02:01:02:01_0_rp_T_1_DPB1*02:01:02:01 
         GCCCCCTCCCCGCAGAGAATTAccttttccagggacggcaggaatgctacgcgtttaatgggacacagcgcttcct
         ggagagatacatctacaaccgggaggagttcgtgcgcttcGACAGCGACGTGGGGGAGTTCC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 1.5868 ± 0, Mean Tm: 59.8 ± 0.4 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                 

T1: DPB1*02:01:02:01_1    1.5868        137       60.0 / 59.5    5'-GCCCCCTCCCCGCAGAGAATTA-3' / 5'-GAACTCCCCCACGTCGCTGTC-3'


* Template 1: DPB1*02:01:02:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPB1*02:01:02:01_1_fp + DPB1*02:01:02:01_1_rp ==> T1: DPB1*02:01:02:01

           PPC = 96.7%, Size = 137 bp, GC content = 58.4%
           FP: 3'ΔG = -0.1(kcal/mol), Tm = 60.0 (°C)
           RP: 3'ΔG = -2.2(kcal/mol), Tm = 59.5 (°C)
           Binding sites: 9(22/22) ... 145(21/21)
         
         >>>DPB1*02:01:02:01_1_fp
            1                    22
         5' GCCCCCTCCCCGCAGAGAATTA 3'
            ||||||||||||||||||||||                                                   145
         5' GCCCCCTCCCCGCAGAGAATTAccttttccagggac...agttcgtgcgcttcGACAGCGACGTGGGGGAGTTC 3'
            9                                                    |||||||||||||||||||||
                                                              3' GACAGCGACGTGGGGGAGTTC 5'
                                                                 21                  1
                                                                 DPB1*02:01:02:01_1_rp<<<
         

         >17_DPB1*02:01:02:01_1_fp_DPB1*02:01:02:01_1_rp_T_1_DPB1*02:01:02:01 
         GCCCCCTCCCCGCAGAGAATTAccttttccagggacggcaggaatgctacgcgtttaatgggacacagcgcttcct
         ggagagatacatctacaaccgggaggagttcgtgcgcttcGACAGCGACGTGGGGGAGTTC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 1.7099 ± 0, Mean Tm: 60.9 ± 1.1 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DPB1*02:01:02:01_2    1.7099        137       60.0 / 61.7    5'-GCCCCCTCCCCGCAGAGAATTA-3' / 5'-GAACTCCCCCACGTCGCTGTCG-3'


* Template 1: DPB1*02:01:02:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPB1*02:01:02:01_2_fp + DPB1*02:01:02:01_2_rp ==> T1: DPB1*02:01:02:01

           PPC = 100.0%, Size = 137 bp, GC content = 58.4%
           FP: 3'ΔG = -0.1(kcal/mol), Tm = 60.0 (°C)
           RP: 3'ΔG = -3.0(kcal/mol), Tm = 61.7 (°C)
           Binding sites: 9(22/22) ... 145(22/22)
         
         >>>DPB1*02:01:02:01_2_fp
            1                    22
         5' GCCCCCTCCCCGCAGAGAATTA 3'
            ||||||||||||||||||||||                                                  145
         5' GCCCCCTCCCCGCAGAGAATTAccttttccaggga...agttcgtgcgcttCGACAGCGACGTGGGGGAGTTC 3'
            9                                                  ||||||||||||||||||||||
                                                            3' CGACAGCGACGTGGGGGAGTTC 5'
                                                               22                   1
                                                                 DPB1*02:01:02:01_2_rp<<<
         

         >3_DPB1*02:01:02:01_2_fp_DPB1*02:01:02:01_2_rp_T_1_DPB1*02:01:02:01 
         GCCCCCTCCCCGCAGAGAATTAccttttccagggacggcaggaatgctacgcgtttaatgggacacagcgcttcct
         ggagagatacatctacaaccgggaggagttcgtgcgcttCGACAGCGACGTGGGGGAGTTC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 1.8243 ± 0, Mean Tm: 60.4 ± 0.5 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                 

T1: DPB1*02:01:02:01_3    1.8243        138       60.0 / 60.8    5'-GCCCCCTCCCCGCAGAGAATTA-3' / 5'-GGAACTCCCCCACGTCGCTGT-3'


* Template 1: DPB1*02:01:02:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPB1*02:01:02:01_3_fp + DPB1*02:01:02:01_3_rp ==> T1: DPB1*02:01:02:01

           PPC = 96.7%, Size = 138 bp, GC content = 58.7%
           FP: 3'ΔG = -0.1(kcal/mol), Tm = 60.0 (°C)
           RP: 3'ΔG = -3.1(kcal/mol), Tm = 60.8 (°C)
           Binding sites: 9(22/22) ... 146(21/21)
         
         >>>DPB1*02:01:02:01_3_fp
            1                    22
         5' GCCCCCTCCCCGCAGAGAATTA 3'
            ||||||||||||||||||||||                                                   146
         5' GCCCCCTCCCCGCAGAGAATTAccttttccagggac...gttcgtgcgcttcgACAGCGACGTGGGGGAGTTCC 3'
            9                                                    |||||||||||||||||||||
                                                              3' ACAGCGACGTGGGGGAGTTCC 5'
                                                                 21                  1
                                                                 DPB1*02:01:02:01_3_rp<<<
         

         >24_DPB1*02:01:02:01_3_fp_DPB1*02:01:02:01_3_rp_T_1_DPB1*02:01:02:01 
         GCCCCCTCCCCGCAGAGAATTAccttttccagggacggcaggaatgctacgcgtttaatgggacacagcgcttcct
         ggagagatacatctacaaccgggaggagttcgtgcgcttcgACAGCGACGTGGGGGAGTTCC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 1.8816 ± 0, Mean Tm: 60.4 ± 0.6 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                 

T1: DPB1*02:01:02:01_4    1.8816        134       60.0 / 60.8    5'-GCCCCCTCCCCGCAGAGAATTA-3' / 5'-CTCCCCCACGTCGCTGTCGAA-3'


* Template 1: DPB1*02:01:02:01

   ** Diagram of the binding pattern between the primers and the template

     *** DPB1*02:01:02:01_4_fp + DPB1*02:01:02:01_4_rp ==> T1: DPB1*02:01:02:01

           PPC = 96.7%, Size = 134 bp, GC content = 59.0%
           FP: 3'ΔG = -0.1(kcal/mol), Tm = 60.0 (°C)
           RP: 3'ΔG = -2.4(kcal/mol), Tm = 60.8 (°C)
           Binding sites: 9(22/22) ... 142(21/21)
         
         >>>DPB1*02:01:02:01_4_fp
            1                    22
         5' GCCCCCTCCCCGCAGAGAATTA 3'
            ||||||||||||||||||||||                                                   142
         5' GCCCCCTCCCCGCAGAGAATTAccttttccagggac...aggagttcgtgcgcTTCGACAGCGACGTGGGGGAG 3'
            9                                                    |||||||||||||||||||||
                                                              3' TTCGACAGCGACGTGGGGGAG 5'
                                                                 21                  1
                                                                 DPB1*02:01:02:01_4_rp<<<
         

         >15_DPB1*02:01:02:01_4_fp_DPB1*02:01:02:01_4_rp_T_1_DPB1*02:01:02:01 
         GCCCCCTCCCCGCAGAGAATTAccttttccagggacggcaggaatgctacgcgtttaatgggacacagcgcttcct
         ggagagatacatctacaaccgggaggagttcgtgcgcTTCGACAGCGACGTGGGGGAG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    