MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DQA1*06:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [137]                  [58.7/56.7]         7.6009 ± 0 
2              [137]                  [56.7/56.7]         7.6435 ± 0 
3              [152]                  [60.4/56.7]         7.7102 ± 0 
4              [137]                  [57.5/56.7]         7.8501 ± 0 
5              [136]                  [57.5/56.7]         7.8501 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 7.6009 ± 0, Mean Tm: 57.7 ± 1.4 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                     

T1: DQA1*06:01_0    7.6009        137       58.7 / 56.7    5'-TGTCGTTCCGTCATGATTGCCTCA-3' / 5'-ACCACCGGAGATATCCGAAAAGC-3'


* Template 1: DQA1*06:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*06:01_0_fp + DQA1*06:01_0_rp ==> T1: DQA1*06:01

           PPC = 97.0%, Size = 137 bp, GC content = 34.3%
           FP: 3'ΔG = -2.5(kcal/mol), Tm = 58.7 (°C)
           RP: 3'ΔG = -2.2(kcal/mol), Tm = 56.7 (°C)
           Binding sites: 21(24/24) ... 157(23/23)
         
         >>>DQA1*06:01_0_fp
            1                      24
         5' TGTCGTTCCGTCATGATTGCCTCA 3'
            ||||||||||||||||||||||||                                                 157
         5' TGTCGTTCCGTCATGATTGCCTCAaaaattagtgag...acaacttttgaaGCTTTTCGGATATCTCCGGTGGT 3'
            21                                                 |||||||||||||||||||||||
                                                            3' GCTTTTCGGATATCTCCGGTGGT 5'
                                                               23                    1
                                                                       DQA1*06:01_0_rp<<<
         

         >11_DQA1*06:01_0_fp_DQA1*06:01_0_rp_T_1_DQA1*06:01 
         TGTCGTTCCGTCATGATTGCCTCAaaaattagtgaggtttccatcagtggataattttttattattaaaaatttat
         gaagtgtcattctcaaatttccctgaacaacttttgaaGCTTTTCGGATATCTCCGGTGGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 7.6435 ± 0, Mean Tm: 56.7 ± 0.0 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DQA1*06:01_1    7.6435        137       56.7 / 56.7    5'-TGTCGTTCCGTCATGATTGCCT-3' / 5'-ACCACCGGAGATATCCGAAAAGC-3'


* Template 1: DQA1*06:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*06:01_1_fp + DQA1*06:01_1_rp ==> T1: DQA1*06:01

           PPC = 96.9%, Size = 137 bp, GC content = 34.3%
           FP: 3'ΔG = -3.4(kcal/mol), Tm = 56.7 (°C)
           RP: 3'ΔG = -2.2(kcal/mol), Tm = 56.7 (°C)
           Binding sites: 21(22/22) ... 157(23/23)
         
         >>>DQA1*06:01_1_fp
            1                    22
         5' TGTCGTTCCGTCATGATTGCCT 3'
            ||||||||||||||||||||||                                                   157
         5' TGTCGTTCCGTCATGATTGCCTcaaaaattagtga...aacaacttttgaaGCTTTTCGGATATCTCCGGTGGT 3'
            21                                                 |||||||||||||||||||||||
                                                            3' GCTTTTCGGATATCTCCGGTGGT 5'
                                                               23                    1
                                                                       DQA1*06:01_1_rp<<<
         

         >17_DQA1*06:01_1_fp_DQA1*06:01_1_rp_T_1_DQA1*06:01 
         TGTCGTTCCGTCATGATTGCCTcaaaaattagtgaggtttccatcagtggataattttttattattaaaaatttat
         gaagtgtcattctcaaatttccctgaacaacttttgaaGCTTTTCGGATATCTCCGGTGGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 7.7102 ± 0, Mean Tm: 58.5 ± 2.6 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                      

T1: DQA1*06:01_2    7.7102        152       60.4 / 56.7    5'-GCCTGGAGGTCTCTATGTCGTTCCG-3' / 5'-ACCACCGGAGATATCCGAAAAGC-3'


* Template 1: DQA1*06:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*06:01_2_fp + DQA1*06:01_2_rp ==> T1: DQA1*06:01

           PPC = 94.1%, Size = 152 bp, GC content = 36.8%
           FP: 3'ΔG = -3.0(kcal/mol), Tm = 60.4 (°C)
           RP: 3'ΔG = -2.2(kcal/mol), Tm = 56.7 (°C)
           Binding sites: 6(25/25) ... 157(23/23)
         
         >>>DQA1*06:01_2_fp
            1                       25
         5' GCCTGGAGGTCTCTATGTCGTTCCG 3'
            |||||||||||||||||||||||||                                               157
         5' GCCTGGAGGTCTCTATGTCGTTCCGtcatgattgcc...caacttttgaaGCTTTTCGGATATCTCCGGTGGT 3'
            6                                                 |||||||||||||||||||||||
                                                           3' GCTTTTCGGATATCTCCGGTGGT 5'
                                                              23                    1
                                                                       DQA1*06:01_2_rp<<<
         

         >23_DQA1*06:01_2_fp_DQA1*06:01_2_rp_T_1_DQA1*06:01 
         GCCTGGAGGTCTCTATGTCGTTCCGtcatgattgcctcaaaaattagtgaggtttccatcagtggataatttttta
         ttattaaaaatttatgaagtgtcattctcaaatttccctgaacaacttttgaaGCTTTTCGGATATCTCCGGTGGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 7.8501 ± 0, Mean Tm: 57.1 ± 0.5 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DQA1*06:01_3    7.8501        137       57.5 / 56.7    5'-TGTCGTTCCGTCATGATTGCCTC-3' / 5'-ACCACCGGAGATATCCGAAAAGC-3'


* Template 1: DQA1*06:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*06:01_3_fp + DQA1*06:01_3_rp ==> T1: DQA1*06:01

           PPC = 100.0%, Size = 137 bp, GC content = 34.3%
           FP: 3'ΔG = -3.4(kcal/mol), Tm = 57.5 (°C)
           RP: 3'ΔG = -2.2(kcal/mol), Tm = 56.7 (°C)
           Binding sites: 21(23/23) ... 157(23/23)
         
         >>>DQA1*06:01_3_fp
            1                     23
         5' TGTCGTTCCGTCATGATTGCCTC 3'
            |||||||||||||||||||||||                                                 157
         5' TGTCGTTCCGTCATGATTGCCTCaaaaattagtga...acaacttttgaaGCTTTTCGGATATCTCCGGTGGT 3'
            21                                                |||||||||||||||||||||||
                                                           3' GCTTTTCGGATATCTCCGGTGGT 5'
                                                              23                    1
                                                                       DQA1*06:01_3_rp<<<
         

         >9_DQA1*06:01_3_fp_DQA1*06:01_3_rp_T_1_DQA1*06:01 
         TGTCGTTCCGTCATGATTGCCTCaaaaattagtgaggtttccatcagtggataattttttattattaaaaatttat
         gaagtgtcattctcaaatttccctgaacaacttttgaaGCTTTTCGGATATCTCCGGTGGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 7.8501 ± 0, Mean Tm: 57.1 ± 0.5 (°C)

                               Amplicon       Tm (°C) 
Primer ID           Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DQA1*06:01_4    7.8501        136       57.5 / 56.7    5'-GTCGTTCCGTCATGATTGCCTCA-3' / 5'-ACCACCGGAGATATCCGAAAAGC-3'


* Template 1: DQA1*06:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*06:01_4_fp + DQA1*06:01_4_rp ==> T1: DQA1*06:01

           PPC = 100.0%, Size = 136 bp, GC content = 34.6%
           FP: 3'ΔG = -2.5(kcal/mol), Tm = 57.5 (°C)
           RP: 3'ΔG = -2.2(kcal/mol), Tm = 56.7 (°C)
           Binding sites: 22(23/23) ... 157(23/23)
         
         >>>DQA1*06:01_4_fp
            1                     23
         5' GTCGTTCCGTCATGATTGCCTCA 3'
            |||||||||||||||||||||||                                                 157
         5' GTCGTTCCGTCATGATTGCCTCAaaaattagtgag...acaacttttgaaGCTTTTCGGATATCTCCGGTGGT 3'
            22                                                |||||||||||||||||||||||
                                                           3' GCTTTTCGGATATCTCCGGTGGT 5'
                                                              23                    1
                                                                       DQA1*06:01_4_rp<<<
         

         >5_DQA1*06:01_4_fp_DQA1*06:01_4_rp_T_1_DQA1*06:01 
         GTCGTTCCGTCATGATTGCCTCAaaaattagtgaggtttccatcagtggataattttttattattaaaaatttatg
         aagtgtcattctcaaatttccctgaacaacttttgaaGCTTTTCGGATATCTCCGGTGGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    