MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DQA1*01:01:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [100]                  [61.6/55.3]         11.3305 ± 0
2              [102]                  [59.8/55.3]         11.8737 ± 0
3              [102]                  [57.8/55.3]         11.9146 ± 0
4              [100]                  [60.0/56.0]         11.9885 ± 0
5              [104]                  [59.8/55.2]         12.0001 ± 0



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 11.3305 ± 0, Mean Tm: 58.4 ± 4.5 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                       

T1: DQA1*01:01:01:01_0    11.3305       100       61.6 / 55.3    5'-TGCATCACAAGGGGATTGCCCCG-3' / 5'-GGCCAATTAGAAAAATCCCCTATGGT-3'


* Template 1: DQA1*01:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*01:01:01:01_0_fp + DQA1*01:01:01:01_0_rp ==> T1: DQA1*01:01:01:01

           PPC = 91.3%, Size = 100 bp, GC content = 46.0%
           FP: 3'ΔG = -4.3(kcal/mol), Tm = 61.6 (°C)
           RP: 3'ΔG = -2.2(kcal/mol), Tm = 55.3 (°C)
           Binding sites: 60(23/23) ... 159(26/26)
         
         >>>DQA1*01:01:01:01_0_fp
            1                     23
         5' TGCATCACAAGGGGATTGCCCCG 3'
            |||||||||||||||||||||||                                                  159
         5' TGCATCACAAGGGGATTGCCCCGtctccttccag...actgagatgtcACCATAGGGGATTTTTCTAATTGGCC 3'
            60                                              ||||||||||||||||||||||||||
                                                         3' ACCATAGGGGATTTTTCTAATTGGCC 5'
                                                            26                       1
                                                                 DQA1*01:01:01:01_0_rp<<<
         

         >24_DQA1*01:01:01:01_0_fp_DQA1*01:01:01:01_0_rp_T_1_DQA1*01:01:01:01 
         TGCATCACAAGGGGATTGCCCCGtctccttccagggctcttaatacaaactcttcaactagtaactgagatgtcAC
         CATAGGGGATTTTTCTAATTGGCC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 11.8737 ± 0, Mean Tm: 57.6 ± 3.2 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                         

T1: DQA1*01:01:01:01_1    11.8737       102       59.8 / 55.3    5'-CCACTCTGAGTAGAGGCTGCATCACA-3' / 5'-TCCCCTATGGTGACATCTCAGTTAC-3'


* Template 1: DQA1*01:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*01:01:01:01_1_fp + DQA1*01:01:01:01_1_rp ==> T1: DQA1*01:01:01:01

           PPC = 97.2%, Size = 102 bp, GC content = 50.0%
           FP: 3'ΔG = -2.3(kcal/mol), Tm = 59.8 (°C)
           RP: 3'ΔG = -1.2(kcal/mol), Tm = 55.3 (°C)
           Binding sites: 43(26/26) ... 144(25/25)
         
         >>>DQA1*01:01:01:01_1_fp
            1                        26
         5' CCACTCTGAGTAGAGGCTGCATCACA 3'
            ||||||||||||||||||||||||||                                               144
         5' CCACTCTGAGTAGAGGCTGCATCACAaggggattgc...tcttcaactaGTAACTGAGATGTCACCATAGGGGA 3'
            43                                               |||||||||||||||||||||||||
                                                          3' GTAACTGAGATGTCACCATAGGGGA 5'
                                                             25                      1
                                                                 DQA1*01:01:01:01_1_rp<<<
         

         >8_DQA1*01:01:01:01_1_fp_DQA1*01:01:01:01_1_rp_T_1_DQA1*01:01:01:01 
         CCACTCTGAGTAGAGGCTGCATCACAaggggattgccccgtctccttccagggctcttaatacaaactcttcaact
         aGTAACTGAGATGTCACCATAGGGGA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 11.9146 ± 0, Mean Tm: 56.5 ± 1.7 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                       

T1: DQA1*01:01:01:01_2    11.9146       102       57.8 / 55.3    5'-CCACTCTGAGTAGAGGCTGCATCA-3' / 5'-TCCCCTATGGTGACATCTCAGTTAC-3'


* Template 1: DQA1*01:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*01:01:01:01_2_fp + DQA1*01:01:01:01_2_rp ==> T1: DQA1*01:01:01:01

           PPC = 97.1%, Size = 102 bp, GC content = 50.0%
           FP: 3'ΔG = -1.7(kcal/mol), Tm = 57.8 (°C)
           RP: 3'ΔG = -1.2(kcal/mol), Tm = 55.3 (°C)
           Binding sites: 43(24/24) ... 144(25/25)
         
         >>>DQA1*01:01:01:01_2_fp
            1                      24
         5' CCACTCTGAGTAGAGGCTGCATCA 3'
            ||||||||||||||||||||||||                                                 144
         5' CCACTCTGAGTAGAGGCTGCATCAcaaggggattg...ctcttcaactaGTAACTGAGATGTCACCATAGGGGA 3'
            43                                               |||||||||||||||||||||||||
                                                          3' GTAACTGAGATGTCACCATAGGGGA 5'
                                                             25                      1
                                                                 DQA1*01:01:01:01_2_rp<<<
         

         >16_DQA1*01:01:01:01_2_fp_DQA1*01:01:01:01_2_rp_T_1_DQA1*01:01:01:01 
         CCACTCTGAGTAGAGGCTGCATCAcaaggggattgccccgtctccttccagggctcttaatacaaactcttcaact
         aGTAACTGAGATGTCACCATAGGGGA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 11.9885 ± 0, Mean Tm: 58.0 ± 2.8 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                          

T1: DQA1*01:01:01:01_3    11.9885       100       60.0 / 56.0    5'-TGAGTAGAGGCTGCATCACAAGGGG-3' / 5'-AAAATCCCCTATGGTGACATCTCAGTT-3'


* Template 1: DQA1*01:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*01:01:01:01_3_fp + DQA1*01:01:01:01_3_rp ==> T1: DQA1*01:01:01:01

           PPC = 94.6%, Size = 100 bp, GC content = 47.0%
           FP: 3'ΔG = -3.4(kcal/mol), Tm = 60.0 (°C)
           RP: 3'ΔG = -1.8(kcal/mol), Tm = 56.0 (°C)
           Binding sites: 49(25/25) ... 148(27/27)
         
         >>>DQA1*01:01:01:01_3_fp
            1                       25
         5' TGAGTAGAGGCTGCATCACAAGGGG 3'
            |||||||||||||||||||||||||                                               148
         5' TGAGTAGAGGCTGCATCACAAGGGGattgccccg...tcaactagtAACTGAGATGTCACCATAGGGGATTTT 3'
            49                                            |||||||||||||||||||||||||||
                                                       3' AACTGAGATGTCACCATAGGGGATTTT 5'
                                                          27                        1
                                                                 DQA1*01:01:01:01_3_rp<<<
         

         >18_DQA1*01:01:01:01_3_fp_DQA1*01:01:01:01_3_rp_T_1_DQA1*01:01:01:01 
         TGAGTAGAGGCTGCATCACAAGGGGattgccccgtctccttccagggctcttaatacaaactcttcaactagtAAC
         TGAGATGTCACCATAGGGGATTTT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 12.0001 ± 0, Mean Tm: 57.5 ± 3.2 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                         

T1: DQA1*01:01:01:01_4    12.0001       104       59.8 / 55.2    5'-CCACTCTGAGTAGAGGCTGCATCACA-3' / 5'-AATCCCCTATGGTGACATCTCAGTT-3'


* Template 1: DQA1*01:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQA1*01:01:01:01_4_fp + DQA1*01:01:01:01_4_rp ==> T1: DQA1*01:01:01:01

           PPC = 97.2%, Size = 104 bp, GC content = 49.0%
           FP: 3'ΔG = -2.3(kcal/mol), Tm = 59.8 (°C)
           RP: 3'ΔG = -1.8(kcal/mol), Tm = 55.2 (°C)
           Binding sites: 43(26/26) ... 146(25/25)
         
         >>>DQA1*01:01:01:01_4_fp
            1                        26
         5' CCACTCTGAGTAGAGGCTGCATCACA 3'
            ||||||||||||||||||||||||||                                               146
         5' CCACTCTGAGTAGAGGCTGCATCACAaggggattgc...ttcaactagtAACTGAGATGTCACCATAGGGGATT 3'
            43                                               |||||||||||||||||||||||||
                                                          3' AACTGAGATGTCACCATAGGGGATT 5'
                                                             25                      1
                                                                 DQA1*01:01:01:01_4_rp<<<
         

         >13_DQA1*01:01:01:01_4_fp_DQA1*01:01:01:01_4_rp_T_1_DQA1*01:01:01:01 
         CCACTCTGAGTAGAGGCTGCATCACAaggggattgccccgtctccttccagggctcttaatacaaactcttcaact
         agtAACTGAGATGTCACCATAGGGGATT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    