MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DQB1*02:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [130]                  [57.5/58.6]         7.8476 ± 0 
2              [130]                  [57.5/57.6]         7.8613 ± 0 
3              [135]                  [59.8/58.6]         8.5069 ± 0 
4              [135]                  [59.8/57.6]         8.5207 ± 0 
5              [130]                  [57.5/58.9]         8.5621 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 7.8476 ± 0, Mean Tm: 58.1 ± 0.8 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                      

T1: DQB1*02:01:01_0    7.8476        130       57.5 / 58.6    5'-TTGAAAGACGTCACAGTGCCAGG-3' / 5'-TGGTAGGATTGGATGGTCCCTTGGA-3'


* Template 1: DQB1*02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQB1*02:01:01_0_fp + DQB1*02:01:01_0_rp ==> T1: DQB1*02:01:01

           PPC = 94.1%, Size = 130 bp, GC content = 47.7%
           FP: 3'ΔG = -3.1(kcal/mol), Tm = 57.5 (°C)
           RP: 3'ΔG = -2.2(kcal/mol), Tm = 58.6 (°C)
           Binding sites: 30(23/23) ... 159(25/25)
         
         >>>DQB1*02:01:01_0_fp
            1                     23
         5' TTGAAAGACGTCACAGTGCCAGG 3'
            |||||||||||||||||||||||                                                 159
         5' TTGAAAGACGTCACAGTGCCAGGcactggattca...attggttccttTCCAAGGGACCATCCAATCCTACCA 3'
            30                                              |||||||||||||||||||||||||
                                                         3' TCCAAGGGACCATCCAATCCTACCA 5'
                                                            25                      1
                                                                    DQB1*02:01:01_0_rp<<<
         

         >17_DQB1*02:01:01_0_fp_DQB1*02:01:01_0_rp_T_1_DQB1*02:01:01 
         TTGAAAGACGTCACAGTGCCAGGcactggattcagaaccttcacaaaaaaaaaatctgcccagagacagatgaggt
         ccttcagctccagtgctgattggttccttTCCAAGGGACCATCCAATCCTACCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 7.8613 ± 0, Mean Tm: 57.6 ± 0.1 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                     

T1: DQB1*02:01:01_1    7.8613        130       57.5 / 57.6    5'-TTGAAAGACGTCACAGTGCCAGG-3' / 5'-TGGTAGGATTGGATGGTCCCTTGG-3'


* Template 1: DQB1*02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQB1*02:01:01_1_fp + DQB1*02:01:01_1_rp ==> T1: DQB1*02:01:01

           PPC = 97.0%, Size = 130 bp, GC content = 47.7%
           FP: 3'ΔG = -3.1(kcal/mol), Tm = 57.5 (°C)
           RP: 3'ΔG = -2.3(kcal/mol), Tm = 57.6 (°C)
           Binding sites: 30(23/23) ... 159(24/24)
         
         >>>DQB1*02:01:01_1_fp
            1                     23
         5' TTGAAAGACGTCACAGTGCCAGG 3'
            |||||||||||||||||||||||                                                  159
         5' TTGAAAGACGTCACAGTGCCAGGcactggattcag...attggttcctttCCAAGGGACCATCCAATCCTACCA 3'
            30                                                ||||||||||||||||||||||||
                                                           3' CCAAGGGACCATCCAATCCTACCA 5'
                                                              24                     1
                                                                    DQB1*02:01:01_1_rp<<<
         

         >9_DQB1*02:01:01_1_fp_DQB1*02:01:01_1_rp_T_1_DQB1*02:01:01 
         TTGAAAGACGTCACAGTGCCAGGcactggattcagaaccttcacaaaaaaaaaatctgcccagagacagatgaggt
         ccttcagctccagtgctgattggttcctttCCAAGGGACCATCCAATCCTACCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 8.5069 ± 0, Mean Tm: 59.2 ± 0.9 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                         

T1: DQB1*02:01:01_2    8.5069        135       59.8 / 58.6    5'-TGCAATTGAAAGACGTCACAGTGCCA-3' / 5'-TGGTAGGATTGGATGGTCCCTTGGA-3'


* Template 1: DQB1*02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQB1*02:01:01_2_fp + DQB1*02:01:01_2_rp ==> T1: DQB1*02:01:01

           PPC = 97.2%, Size = 135 bp, GC content = 47.4%
           FP: 3'ΔG = -3.6(kcal/mol), Tm = 59.8 (°C)
           RP: 3'ΔG = -2.2(kcal/mol), Tm = 58.6 (°C)
           Binding sites: 25(26/26) ... 159(25/25)
         
         >>>DQB1*02:01:01_2_fp
            1                        26
         5' TGCAATTGAAAGACGTCACAGTGCCA 3'
            ||||||||||||||||||||||||||                                               159
         5' TGCAATTGAAAGACGTCACAGTGCCAggcactggat...ttggttccttTCCAAGGGACCATCCAATCCTACCA 3'
            25                                               |||||||||||||||||||||||||
                                                          3' TCCAAGGGACCATCCAATCCTACCA 5'
                                                             25                      1
                                                                    DQB1*02:01:01_2_rp<<<
         

         >4_DQB1*02:01:01_2_fp_DQB1*02:01:01_2_rp_T_1_DQB1*02:01:01 
         TGCAATTGAAAGACGTCACAGTGCCAggcactggattcagaaccttcacaaaaaaaaaatctgcccagagacagat
         gaggtccttcagctccagtgctgattggttccttTCCAAGGGACCATCCAATCCTACCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 8.5207 ± 0, Mean Tm: 58.7 ± 1.6 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                        

T1: DQB1*02:01:01_3    8.5207        135       59.8 / 57.6    5'-TGCAATTGAAAGACGTCACAGTGCCA-3' / 5'-TGGTAGGATTGGATGGTCCCTTGG-3'


* Template 1: DQB1*02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQB1*02:01:01_3_fp + DQB1*02:01:01_3_rp ==> T1: DQB1*02:01:01

           PPC = 94.3%, Size = 135 bp, GC content = 47.4%
           FP: 3'ΔG = -3.6(kcal/mol), Tm = 59.8 (°C)
           RP: 3'ΔG = -2.3(kcal/mol), Tm = 57.6 (°C)
           Binding sites: 25(26/26) ... 159(24/24)
         
         >>>DQB1*02:01:01_3_fp
            1                        26
         5' TGCAATTGAAAGACGTCACAGTGCCA 3'
            ||||||||||||||||||||||||||                                              159
         5' TGCAATTGAAAGACGTCACAGTGCCAggcactggat...tggttcctttCCAAGGGACCATCCAATCCTACCA 3'
            25                                               ||||||||||||||||||||||||
                                                          3' CCAAGGGACCATCCAATCCTACCA 5'
                                                             24                     1
                                                                    DQB1*02:01:01_3_rp<<<
         

         >16_DQB1*02:01:01_3_fp_DQB1*02:01:01_3_rp_T_1_DQB1*02:01:01 
         TGCAATTGAAAGACGTCACAGTGCCAggcactggattcagaaccttcacaaaaaaaaaatctgcccagagacagat
         gaggtccttcagctccagtgctgattggttcctttCCAAGGGACCATCCAATCCTACCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 8.5621 ± 0, Mean Tm: 58.2 ± 1.0 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                       

T1: DQB1*02:01:01_4    8.5621        130       57.5 / 58.9    5'-TTGAAAGACGTCACAGTGCCAGG-3' / 5'-TGGTAGGATTGGATGGTCCCTTGGAA-3'


* Template 1: DQB1*02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DQB1*02:01:01_4_fp + DQB1*02:01:01_4_rp ==> T1: DQB1*02:01:01

           PPC = 91.3%, Size = 130 bp, GC content = 47.7%
           FP: 3'ΔG = -3.1(kcal/mol), Tm = 57.5 (°C)
           RP: 3'ΔG = -2.2(kcal/mol), Tm = 58.9 (°C)
           Binding sites: 30(23/23) ... 159(26/26)
         
         >>>DQB1*02:01:01_4_fp
            1                     23
         5' TTGAAAGACGTCACAGTGCCAGG 3'
            |||||||||||||||||||||||                                                  159
         5' TTGAAAGACGTCACAGTGCCAGGcactggattca...gattggttcctTTCCAAGGGACCATCCAATCCTACCA 3'
            30                                              ||||||||||||||||||||||||||
                                                         3' TTCCAAGGGACCATCCAATCCTACCA 5'
                                                            26                       1
                                                                    DQB1*02:01:01_4_rp<<<
         

         >25_DQB1*02:01:01_4_fp_DQB1*02:01:01_4_rp_T_1_DQB1*02:01:01 
         TTGAAAGACGTCACAGTGCCAGGcactggattcagaaccttcacaaaaaaaaaatctgcccagagacagatgaggt
         ccttcagctccagtgctgattggttcctTTCCAAGGGACCATCCAATCCTACCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    