MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DRB1-02region

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [150]                  [60.9/60.1]         1.9205 ± 0 
2              [149]                  [60.9/58.8]         2.0991 ± 0 
3              [149]                  [60.2/60.1]         2.2972 ± 0 
4              [151]                  [60.3/60.1]         2.3620 ± 0 
5              [152]                  [61.3/60.1]         2.3747 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 1.9205 ± 0, Mean Tm: 60.5 ± 0.6 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DRB1-02region_0    1.9205        150       60.9 / 60.1    5'-GACAGCGACGTGGGGGAGTACC-3' / 5'-TGTGAAGCTCTCACCAACCCCGT-3'


* Template 1: DRB1-02region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-02region_0_fp + DRB1-02region_0_rp ==> T1: DRB1-02region

           PPC = 96.9%, Size = 150 bp, GC content = 65.3%
           FP: 3'ΔG = -2.0(kcal/mol), Tm = 60.9 (°C)
           RP: 3'ΔG = -3.9(kcal/mol), Tm = 60.1 (°C)
           Binding sites: 6(22/22) ... 155(23/23)
         
         >>>DRB1-02region_0_fp
            1                    22
         5' GACAGCGACGTGGGGGAGTACC 3'
            ||||||||||||||||||||||                                                   155
         5' GACAGCGACGTGGGGGAGTACCgggcggtgacgga...tgcagacacaactACGGGGTTGGTGAGAGCTTCACA 3'
            6                                                  |||||||||||||||||||||||
                                                            3' ACGGGGTTGGTGAGAGCTTCACA 5'
                                                               23                    1
                                                                    DRB1-02region_0_rp<<<
         

         >4_DRB1-02region_0_fp_DRB1-02region_0_rp_T_1_DRB1-02region 
         GACAGCGACGTGGGGGAGTACCgggcggtgacggagctggggcggcctgatgccgagtactggaacagccagaagg
         acctcctggagcagaggcgggccgcggtggacacctactgcagacacaactACGGGGTTGGTGAGAGCTTCACA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 2.0991 ± 0, Mean Tm: 59.8 ± 1.5 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1-02region_1    2.0991        149       60.9 / 58.8    5'-GACAGCGACGTGGGGGAGTACC-3' / 5'-GTGAAGCTCTCACCAACCCCGT-3'


* Template 1: DRB1-02region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-02region_1_fp + DRB1-02region_1_rp ==> T1: DRB1-02region

           PPC = 100.0%, Size = 149 bp, GC content = 65.8%
           FP: 3'ΔG = -2.0(kcal/mol), Tm = 60.9 (°C)
           RP: 3'ΔG = -3.9(kcal/mol), Tm = 58.8 (°C)
           Binding sites: 6(22/22) ... 154(22/22)
         
         >>>DRB1-02region_1_fp
            1                    22
         5' GACAGCGACGTGGGGGAGTACC 3'
            ||||||||||||||||||||||                                                  154
         5' GACAGCGACGTGGGGGAGTACCgggcggtgacgga...tgcagacacaactACGGGGTTGGTGAGAGCTTCAC 3'
            6                                                  ||||||||||||||||||||||
                                                            3' ACGGGGTTGGTGAGAGCTTCAC 5'
                                                               22                   1
                                                                    DRB1-02region_1_rp<<<
         

         >2_DRB1-02region_1_fp_DRB1-02region_1_rp_T_1_DRB1-02region 
         GACAGCGACGTGGGGGAGTACCgggcggtgacggagctggggcggcctgatgccgagtactggaacagccagaagg
         acctcctggagcagaggcgggccgcggtggacacctactgcagacacaactACGGGGTTGGTGAGAGCTTCAC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 2.2972 ± 0, Mean Tm: 60.1 ± 0.1 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1-02region_2    2.2972        149       60.2 / 60.1    5'-ACAGCGACGTGGGGGAGTACC-3' / 5'-TGTGAAGCTCTCACCAACCCCGT-3'


* Template 1: DRB1-02region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-02region_2_fp + DRB1-02region_2_rp ==> T1: DRB1-02region

           PPC = 93.6%, Size = 149 bp, GC content = 65.1%
           FP: 3'ΔG = -2.0(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -3.9(kcal/mol), Tm = 60.1 (°C)
           Binding sites: 7(21/21) ... 155(23/23)
         
         >>>DRB1-02region_2_fp
            1                   21
         5' ACAGCGACGTGGGGGAGTACC 3'
            |||||||||||||||||||||                                                   155
         5' ACAGCGACGTGGGGGAGTACCgggcggtgacgga...tgcagacacaactACGGGGTTGGTGAGAGCTTCACA 3'
            7                                                 |||||||||||||||||||||||
                                                           3' ACGGGGTTGGTGAGAGCTTCACA 5'
                                                              23                    1
                                                                    DRB1-02region_2_rp<<<
         

         >19_DRB1-02region_2_fp_DRB1-02region_2_rp_T_1_DRB1-02region 
         ACAGCGACGTGGGGGAGTACCgggcggtgacggagctggggcggcctgatgccgagtactggaacagccagaagga
         cctcctggagcagaggcgggccgcggtggacacctactgcagacacaactACGGGGTTGGTGAGAGCTTCACA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 2.3620 ± 0, Mean Tm: 60.2 ± 0.2 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1-02region_3    2.362         151       60.3 / 60.1    5'-CGACAGCGACGTGGGGGAGTA-3' / 5'-TGTGAAGCTCTCACCAACCCCGT-3'


* Template 1: DRB1-02region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-02region_3_fp + DRB1-02region_3_rp ==> T1: DRB1-02region

           PPC = 93.6%, Size = 151 bp, GC content = 65.6%
           FP: 3'ΔG = -1.3(kcal/mol), Tm = 60.3 (°C)
           RP: 3'ΔG = -3.9(kcal/mol), Tm = 60.1 (°C)
           Binding sites: 5(21/21) ... 155(23/23)
         
         >>>DRB1-02region_3_fp
            1                   21
         5' CGACAGCGACGTGGGGGAGTA 3'
            |||||||||||||||||||||                                                   155
         5' CGACAGCGACGTGGGGGAGTAccgggcggtgacg...tgcagacacaactACGGGGTTGGTGAGAGCTTCACA 3'
            5                                                 |||||||||||||||||||||||
                                                           3' ACGGGGTTGGTGAGAGCTTCACA 5'
                                                              23                    1
                                                                    DRB1-02region_3_rp<<<
         

         >24_DRB1-02region_3_fp_DRB1-02region_3_rp_T_1_DRB1-02region 
         CGACAGCGACGTGGGGGAGTAccgggcggtgacggagctggggcggcctgatgccgagtactggaacagccagaag
         gacctcctggagcagaggcgggccgcggtggacacctactgcagacacaactACGGGGTTGGTGAGAGCTTCACA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 2.3747 ± 0, Mean Tm: 60.7 ± 0.9 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DRB1-02region_4    2.3747        152       61.3 / 60.1    5'-TCGACAGCGACGTGGGGGAGTA-3' / 5'-TGTGAAGCTCTCACCAACCCCGT-3'


* Template 1: DRB1-02region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-02region_4_fp + DRB1-02region_4_rp ==> T1: DRB1-02region

           PPC = 96.9%, Size = 152 bp, GC content = 65.1%
           FP: 3'ΔG = -1.3(kcal/mol), Tm = 61.3 (°C)
           RP: 3'ΔG = -3.9(kcal/mol), Tm = 60.1 (°C)
           Binding sites: 4(22/22) ... 155(23/23)
         
         >>>DRB1-02region_4_fp
            1                    22
         5' TCGACAGCGACGTGGGGGAGTA 3'
            ||||||||||||||||||||||                                                   155
         5' TCGACAGCGACGTGGGGGAGTAccgggcggtgacg...tgcagacacaactACGGGGTTGGTGAGAGCTTCACA 3'
            4                                                  |||||||||||||||||||||||
                                                            3' ACGGGGTTGGTGAGAGCTTCACA 5'
                                                               23                    1
                                                                    DRB1-02region_4_rp<<<
         

         >15_DRB1-02region_4_fp_DRB1-02region_4_rp_T_1_DRB1-02region 
         TCGACAGCGACGTGGGGGAGTAccgggcggtgacggagctggggcggcctgatgccgagtactggaacagccagaa
         ggacctcctggagcagaggcgggccgcggtggacacctactgcagacacaactACGGGGTTGGTGAGAGCTTCACA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    