MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DRB1*11:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [133]                  [59.8/58.1]         3.0648 ± 0 
2              [143]                  [59.8/59.0]         3.1656 ± 0 
3              [144]                  [59.8/59.0]         3.1663 ± 0 
4              [133]                  [59.8/58.8]         3.3564 ± 0 
5              [133]                  [59.8/59.8]         3.3827 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 3.0648 ± 0, Mean Tm: 59.0 ± 1.2 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DRB1*11:01:01_0    3.0648        133       59.8 / 58.1    5'-TCTCCTGACCTCGTGATCCGCC-3' / 5'-ACCCCAACAATCCAATCCCCACA-3'


* Template 1: DRB1*11:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*11:01:01_0_fp + DRB1*11:01:01_0_rp ==> T1: DRB1*11:01:01

           PPC = 96.9%, Size = 133 bp, GC content = 51.1%
           FP: 3'ΔG = -4.7(kcal/mol), Tm = 59.8 (°C)
           RP: 3'ΔG = -2.8(kcal/mol), Tm = 58.1 (°C)
           Binding sites: 13(22/22) ... 145(23/23)
         
         >>>DRB1*11:01:01_0_fp
            1                    22
         5' TCTCCTGACCTCGTGATCCGCC 3'
            ||||||||||||||||||||||                                                   145
         5' TCTCCTGACCTCGTGATCCGCCcgccttggcctcc...attctagctactcTGTGGGGATTGGATTGTTGGGGT 3'
            13                                                 |||||||||||||||||||||||
                                                            3' TGTGGGGATTGGATTGTTGGGGT 5'
                                                               23                    1
                                                                    DRB1*11:01:01_0_rp<<<
         

         >1_DRB1*11:01:01_0_fp_DRB1*11:01:01_0_rp_T_1_DRB1*11:01:01 
         TCTCCTGACCTCGTGATCCGCCcgccttggcctcccaaagtgctgggattataggcgtgagccactgcacccggcc
         tatattcaatttttaaaactaattctagctactcTGTGGGGATTGGATTGTTGGGGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 3.1656 ± 0, Mean Tm: 59.4 ± 0.5 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DRB1*11:01:01_1    3.1656        143       59.8 / 59.0    5'-TCTCCTGACCTCGTGATCCGCC-3' / 5'-CCACTGGTGAACCCCAACAATCCA-3'


* Template 1: DRB1*11:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*11:01:01_1_fp + DRB1*11:01:01_1_rp ==> T1: DRB1*11:01:01

           PPC = 93.9%, Size = 143 bp, GC content = 51.7%
           FP: 3'ΔG = -4.7(kcal/mol), Tm = 59.8 (°C)
           RP: 3'ΔG = -2.1(kcal/mol), Tm = 59.0 (°C)
           Binding sites: 13(22/22) ... 155(24/24)
         
         >>>DRB1*11:01:01_1_fp
            1                    22
         5' TCTCCTGACCTCGTGATCCGCC 3'
            ||||||||||||||||||||||                                                  155
         5' TCTCCTGACCTCGTGATCCGCCcgccttggcctc...ctctgtggggatTGGATTGTTGGGGTTCACCAGTGG 3'
            13                                               ||||||||||||||||||||||||
                                                          3' TGGATTGTTGGGGTTCACCAGTGG 5'
                                                             24                     1
                                                                    DRB1*11:01:01_1_rp<<<
         

         >12_DRB1*11:01:01_1_fp_DRB1*11:01:01_1_rp_T_1_DRB1*11:01:01 
         TCTCCTGACCTCGTGATCCGCCcgccttggcctcccaaagtgctgggattataggcgtgagccactgcacccggcc
         tatattcaatttttaaaactaattctagctactctgtggggatTGGATTGTTGGGGTTCACCAGTGG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 3.1663 ± 0, Mean Tm: 59.4 ± 0.5 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DRB1*11:01:01_2    3.1663        144       59.8 / 59.0    5'-TCTCCTGACCTCGTGATCCGCC-3' / 5'-ACCACTGGTGAACCCCAACAATCC-3'


* Template 1: DRB1*11:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*11:01:01_2_fp + DRB1*11:01:01_2_rp ==> T1: DRB1*11:01:01

           PPC = 93.9%, Size = 144 bp, GC content = 51.4%
           FP: 3'ΔG = -4.7(kcal/mol), Tm = 59.8 (°C)
           RP: 3'ΔG = -1.7(kcal/mol), Tm = 59.0 (°C)
           Binding sites: 13(22/22) ... 156(24/24)
         
         >>>DRB1*11:01:01_2_fp
            1                    22
         5' TCTCCTGACCTCGTGATCCGCC 3'
            ||||||||||||||||||||||                                                  156
         5' TCTCCTGACCTCGTGATCCGCCcgccttggcctc...tctgtggggattGGATTGTTGGGGTTCACCAGTGGT 3'
            13                                               ||||||||||||||||||||||||
                                                          3' GGATTGTTGGGGTTCACCAGTGGT 5'
                                                             24                     1
                                                                    DRB1*11:01:01_2_rp<<<
         

         >18_DRB1*11:01:01_2_fp_DRB1*11:01:01_2_rp_T_1_DRB1*11:01:01 
         TCTCCTGACCTCGTGATCCGCCcgccttggcctcccaaagtgctgggattataggcgtgagccactgcacccggcc
         tatattcaatttttaaaactaattctagctactctgtggggattGGATTGTTGGGGTTCACCAGTGGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 3.3564 ± 0, Mean Tm: 59.3 ± 0.7 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DRB1*11:01:01_3    3.3564        133       59.8 / 58.8    5'-TCTCCTGACCTCGTGATCCGCC-3' / 5'-ACCCCAACAATCCAATCCCCACAG-3'


* Template 1: DRB1*11:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*11:01:01_3_fp + DRB1*11:01:01_3_rp ==> T1: DRB1*11:01:01

           PPC = 93.9%, Size = 133 bp, GC content = 51.1%
           FP: 3'ΔG = -4.7(kcal/mol), Tm = 59.8 (°C)
           RP: 3'ΔG = -2.4(kcal/mol), Tm = 58.8 (°C)
           Binding sites: 13(22/22) ... 145(24/24)
         
         >>>DRB1*11:01:01_3_fp
            1                    22
         5' TCTCCTGACCTCGTGATCCGCC 3'
            ||||||||||||||||||||||                                                  145
         5' TCTCCTGACCTCGTGATCCGCCcgccttggcctc...attctagctactCTGTGGGGATTGGATTGTTGGGGT 3'
            13                                               ||||||||||||||||||||||||
                                                          3' CTGTGGGGATTGGATTGTTGGGGT 5'
                                                             24                     1
                                                                    DRB1*11:01:01_3_rp<<<
         

         >9_DRB1*11:01:01_3_fp_DRB1*11:01:01_3_rp_T_1_DRB1*11:01:01 
         TCTCCTGACCTCGTGATCCGCCcgccttggcctcccaaagtgctgggattataggcgtgagccactgcacccggcc
         tatattcaatttttaaaactaattctagctactCTGTGGGGATTGGATTGTTGGGGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 3.3827 ± 0, Mean Tm: 59.8 ± 0.0 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                     

T1: DRB1*11:01:01_4    3.3827        133       59.8 / 59.8    5'-TCTCCTGACCTCGTGATCCGCC-3' / 5'-ACCCCAACAATCCAATCCCCACAGA-3'


* Template 1: DRB1*11:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*11:01:01_4_fp + DRB1*11:01:01_4_rp ==> T1: DRB1*11:01:01

           PPC = 91.0%, Size = 133 bp, GC content = 51.1%
           FP: 3'ΔG = -4.7(kcal/mol), Tm = 59.8 (°C)
           RP: 3'ΔG = -2.1(kcal/mol), Tm = 59.8 (°C)
           Binding sites: 13(22/22) ... 145(25/25)
         
         >>>DRB1*11:01:01_4_fp
            1                    22
         5' TCTCCTGACCTCGTGATCCGCC 3'
            ||||||||||||||||||||||                                                   145
         5' TCTCCTGACCTCGTGATCCGCCcgccttggcctc...aattctagctacTCTGTGGGGATTGGATTGTTGGGGT 3'
            13                                               |||||||||||||||||||||||||
                                                          3' TCTGTGGGGATTGGATTGTTGGGGT 5'
                                                             25                      1
                                                                    DRB1*11:01:01_4_rp<<<
         

         >25_DRB1*11:01:01_4_fp_DRB1*11:01:01_4_rp_T_1_DRB1*11:01:01 
         TCTCCTGACCTCGTGATCCGCCcgccttggcctcccaaagtgctgggattataggcgtgagccactgcacccggcc
         tatattcaatttttaaaactaattctagctacTCTGTGGGGATTGGATTGTTGGGGT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    