MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DRB1*04:01:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [136]                  [59.7/59.3]         0.9211 ± 0 
2              [135]                  [59.7/59.3]         0.9211 ± 0 
3              [135]                  [59.7/60.0]         1.2711 ± 0 
4              [136]                  [59.7/60.4]         1.6282 ± 0 
5              [137]                  [59.8/59.3]         1.8442 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 0.9211 ± 0, Mean Tm: 59.5 ± 0.3 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*04:01:01:01_0    0.9211        136       59.7 / 59.3    5'-TTACAGGCGTGAGCCACCATGC-3' / 5'-AGCCTGGGCAACAGAGCAAGAC-3'


* Template 1: DRB1*04:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*04:01:01:01_0_fp + DRB1*04:01:01:01_0_rp ==> T1: DRB1*04:01:01:01

           PPC = 100.0%, Size = 136 bp, GC content = 39.0%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.7 (°C)
           RP: 3'ΔG = -1.7(kcal/mol), Tm = 59.3 (°C)
           Binding sites: 16(22/22) ... 151(22/22)
         
         >>>DRB1*04:01:01:01_0_fp
            1                    22
         5' TTACAGGCGTGAGCCACCATGC 3'
            ||||||||||||||||||||||                                                  151
         5' TTACAGGCGTGAGCCACCATGCccaacctgaattt...tttttgagacagaGTCTTGCTCTGTTGCCCAGGCT 3'
            16                                                 ||||||||||||||||||||||
                                                            3' GTCTTGCTCTGTTGCCCAGGCT 5'
                                                               22                   1
                                                                 DRB1*04:01:01:01_0_rp<<<
         

         >5_DRB1*04:01:01:01_0_fp_DRB1*04:01:01:01_0_rp_T_1_DRB1*04:01:01:01 
         TTACAGGCGTGAGCCACCATGCccaacctgaattttatttgaatagatatgagaagctactgtatggttacaagga
         cagtcaatttatattcgattttttttttttgagacagaGTCTTGCTCTGTTGCCCAGGCT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 0.9211 ± 0, Mean Tm: 59.5 ± 0.3 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*04:01:01:01_1    0.9211        135       59.7 / 59.3    5'-TTACAGGCGTGAGCCACCATGC-3' / 5'-GCCTGGGCAACAGAGCAAGACT-3'


* Template 1: DRB1*04:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*04:01:01:01_1_fp + DRB1*04:01:01:01_1_rp ==> T1: DRB1*04:01:01:01

           PPC = 100.0%, Size = 135 bp, GC content = 39.3%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.7 (°C)
           RP: 3'ΔG = -1.9(kcal/mol), Tm = 59.3 (°C)
           Binding sites: 16(22/22) ... 150(22/22)
         
         >>>DRB1*04:01:01:01_1_fp
            1                    22
         5' TTACAGGCGTGAGCCACCATGC 3'
            ||||||||||||||||||||||                                                  150
         5' TTACAGGCGTGAGCCACCATGCccaacctgaattt...ttttttgagacagAGTCTTGCTCTGTTGCCCAGGC 3'
            16                                                 ||||||||||||||||||||||
                                                            3' AGTCTTGCTCTGTTGCCCAGGC 5'
                                                               22                   1
                                                                 DRB1*04:01:01:01_1_rp<<<
         

         >2_DRB1*04:01:01:01_1_fp_DRB1*04:01:01:01_1_rp_T_1_DRB1*04:01:01:01 
         TTACAGGCGTGAGCCACCATGCccaacctgaattttatttgaatagatatgagaagctactgtatggttacaagga
         cagtcaatttatattcgattttttttttttgagacagAGTCTTGCTCTGTTGCCCAGGC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 1.2711 ± 0, Mean Tm: 59.9 ± 0.2 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DRB1*04:01:01:01_2    1.2711        135       59.7 / 60.0    5'-TTACAGGCGTGAGCCACCATGC-3' / 5'-GCCTGGGCAACAGAGCAAGACTC-3'


* Template 1: DRB1*04:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*04:01:01:01_2_fp + DRB1*04:01:01:01_2_rp ==> T1: DRB1*04:01:01:01

           PPC = 96.9%, Size = 135 bp, GC content = 39.3%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.7 (°C)
           RP: 3'ΔG = -2.1(kcal/mol), Tm = 60.0 (°C)
           Binding sites: 16(22/22) ... 150(23/23)
         
         >>>DRB1*04:01:01:01_2_fp
            1                    22
         5' TTACAGGCGTGAGCCACCATGC 3'
            ||||||||||||||||||||||                                                   150
         5' TTACAGGCGTGAGCCACCATGCccaacctgaattt...tttttttgagacaGAGTCTTGCTCTGTTGCCCAGGC 3'
            16                                                 |||||||||||||||||||||||
                                                            3' GAGTCTTGCTCTGTTGCCCAGGC 5'
                                                               23                    1
                                                                 DRB1*04:01:01:01_2_rp<<<
         

         >17_DRB1*04:01:01:01_2_fp_DRB1*04:01:01:01_2_rp_T_1_DRB1*04:01:01:01 
         TTACAGGCGTGAGCCACCATGCccaacctgaattttatttgaatagatatgagaagctactgtatggttacaagga
         cagtcaatttatattcgattttttttttttgagacaGAGTCTTGCTCTGTTGCCCAGGC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 1.6282 ± 0, Mean Tm: 60.0 ± 0.4 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DRB1*04:01:01:01_3    1.6282        136       59.7 / 60.4    5'-TTACAGGCGTGAGCCACCATGC-3' / 5'-AGCCTGGGCAACAGAGCAAGACT-3'


* Template 1: DRB1*04:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*04:01:01:01_3_fp + DRB1*04:01:01:01_3_rp ==> T1: DRB1*04:01:01:01

           PPC = 96.9%, Size = 136 bp, GC content = 39.0%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.7 (°C)
           RP: 3'ΔG = -1.9(kcal/mol), Tm = 60.4 (°C)
           Binding sites: 16(22/22) ... 151(23/23)
         
         >>>DRB1*04:01:01:01_3_fp
            1                    22
         5' TTACAGGCGTGAGCCACCATGC 3'
            ||||||||||||||||||||||                                                   151
         5' TTACAGGCGTGAGCCACCATGCccaacctgaattt...ttttttgagacagAGTCTTGCTCTGTTGCCCAGGCT 3'
            16                                                 |||||||||||||||||||||||
                                                            3' AGTCTTGCTCTGTTGCCCAGGCT 5'
                                                               23                    1
                                                                 DRB1*04:01:01:01_3_rp<<<
         

         >22_DRB1*04:01:01:01_3_fp_DRB1*04:01:01:01_3_rp_T_1_DRB1*04:01:01:01 
         TTACAGGCGTGAGCCACCATGCccaacctgaattttatttgaatagatatgagaagctactgtatggttacaagga
         cagtcaatttatattcgattttttttttttgagacagAGTCTTGCTCTGTTGCCCAGGCT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 1.8442 ± 0, Mean Tm: 59.6 ± 0.3 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DRB1*04:01:01:01_4    1.8442        137       59.8 / 59.3    5'-ATTACAGGCGTGAGCCACCATGC-3' / 5'-AGCCTGGGCAACAGAGCAAGAC-3'


* Template 1: DRB1*04:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*04:01:01:01_4_fp + DRB1*04:01:01:01_4_rp ==> T1: DRB1*04:01:01:01

           PPC = 96.9%, Size = 137 bp, GC content = 38.7%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.8 (°C)
           RP: 3'ΔG = -1.7(kcal/mol), Tm = 59.3 (°C)
           Binding sites: 15(23/23) ... 151(22/22)
         
         >>>DRB1*04:01:01:01_4_fp
            1                     23
         5' ATTACAGGCGTGAGCCACCATGC 3'
            |||||||||||||||||||||||                                                  151
         5' ATTACAGGCGTGAGCCACCATGCccaacctgaattt...tttttgagacagaGTCTTGCTCTGTTGCCCAGGCT 3'
            15                                                  ||||||||||||||||||||||
                                                             3' GTCTTGCTCTGTTGCCCAGGCT 5'
                                                                22                   1
                                                                 DRB1*04:01:01:01_4_rp<<<
         

         >25_DRB1*04:01:01:01_4_fp_DRB1*04:01:01:01_4_rp_T_1_DRB1*04:01:01:01 
         ATTACAGGCGTGAGCCACCATGCccaacctgaattttatttgaatagatatgagaagctactgtatggttacaagg
         acagtcaatttatattcgattttttttttttgagacagaGTCTTGCTCTGTTGCCCAGGCT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    