MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DRB1*07:01:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [101]                  [59.2/55.2]         10.6230 ± 0
2              [102]                  [60.1/55.2]         10.8504 ± 0
3              [101]                  [60.3/55.2]         11.0688 ± 0
4              [101]                  [59.2/55.6]         11.1905 ± 0
5              [100]                  [58.6/55.2]         11.1959 ± 0



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 10.6230 ± 0, Mean Tm: 57.2 ± 2.8 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                       

T1: DRB1*07:01:01:01_0    10.623        101       59.2 / 55.2    5'-CCCACCTATGAGTGAGAACATGCGG-3' / 5'-TGTCCTTTGTAGGGACATGGATGA-3'


* Template 1: DRB1*07:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*07:01:01:01_0_fp + DRB1*07:01:01:01_0_rp ==> T1: DRB1*07:01:01:01

           PPC = 97.1%, Size = 101 bp, GC content = 40.6%
           FP: 3'ΔG = -4.3(kcal/mol), Tm = 59.2 (°C)
           RP: 3'ΔG = -1.6(kcal/mol), Tm = 55.2 (°C)
           Binding sites: 19(25/25) ... 119(24/24)
         
         >>>DRB1*07:01:01:01_0_fp
            1                       25
         5' CCCACCTATGAGTGAGAACATGCGG 3'
            |||||||||||||||||||||||||                                                119
         5' CCCACCTATGAGTGAGAACATGCGGtgtttggtttt...gatttccaattTCATCCATGTCCCTACAAAGGACA 3'
            19                                                ||||||||||||||||||||||||
                                                           3' TCATCCATGTCCCTACAAAGGACA 5'
                                                              24                     1
                                                                 DRB1*07:01:01:01_0_rp<<<
         

         >10_DRB1*07:01:01:01_0_fp_DRB1*07:01:01:01_0_rp_T_1_DRB1*07:01:01:01 
         CCCACCTATGAGTGAGAACATGCGGtgtttggttttttgttcttgcgatagtttactgagaatgatgatttccaat
         tTCATCCATGTCCCTACAAAGGACA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 10.8504 ± 0, Mean Tm: 57.6 ± 3.4 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                        

T1: DRB1*07:01:01:01_1    10.8504       102       60.1 / 55.2    5'-TCCCACCTATGAGTGAGAACATGCGG-3' / 5'-TGTCCTTTGTAGGGACATGGATGA-3'


* Template 1: DRB1*07:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*07:01:01:01_1_fp + DRB1*07:01:01:01_1_rp ==> T1: DRB1*07:01:01:01

           PPC = 94.3%, Size = 102 bp, GC content = 40.2%
           FP: 3'ΔG = -4.3(kcal/mol), Tm = 60.1 (°C)
           RP: 3'ΔG = -1.6(kcal/mol), Tm = 55.2 (°C)
           Binding sites: 18(26/26) ... 119(24/24)
         
         >>>DRB1*07:01:01:01_1_fp
            1                        26
         5' TCCCACCTATGAGTGAGAACATGCGG 3'
            ||||||||||||||||||||||||||                                              119
         5' TCCCACCTATGAGTGAGAACATGCGGtgtttggttt...atttccaattTCATCCATGTCCCTACAAAGGACA 3'
            18                                               ||||||||||||||||||||||||
                                                          3' TCATCCATGTCCCTACAAAGGACA 5'
                                                             24                     1
                                                                 DRB1*07:01:01:01_1_rp<<<
         

         >23_DRB1*07:01:01:01_1_fp_DRB1*07:01:01:01_1_rp_T_1_DRB1*07:01:01:01 
         TCCCACCTATGAGTGAGAACATGCGGtgtttggttttttgttcttgcgatagtttactgagaatgatgatttccaa
         ttTCATCCATGTCCCTACAAAGGACA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 11.0688 ± 0, Mean Tm: 57.7 ± 3.6 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                        

T1: DRB1*07:01:01:01_2    11.0688       101       60.3 / 55.2    5'-CCCACCTATGAGTGAGAACATGCGGT-3' / 5'-TGTCCTTTGTAGGGACATGGATGA-3'


* Template 1: DRB1*07:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*07:01:01:01_2_fp + DRB1*07:01:01:01_2_rp ==> T1: DRB1*07:01:01:01

           PPC = 94.3%, Size = 101 bp, GC content = 40.6%
           FP: 3'ΔG = -4.3(kcal/mol), Tm = 60.3 (°C)
           RP: 3'ΔG = -1.6(kcal/mol), Tm = 55.2 (°C)
           Binding sites: 19(26/26) ... 119(24/24)
         
         >>>DRB1*07:01:01:01_2_fp
            1                        26
         5' CCCACCTATGAGTGAGAACATGCGGT 3'
            ||||||||||||||||||||||||||                                              119
         5' CCCACCTATGAGTGAGAACATGCGGTgtttggtttt...atttccaattTCATCCATGTCCCTACAAAGGACA 3'
            19                                               ||||||||||||||||||||||||
                                                          3' TCATCCATGTCCCTACAAAGGACA 5'
                                                             24                     1
                                                                 DRB1*07:01:01:01_2_rp<<<
         

         >20_DRB1*07:01:01:01_2_fp_DRB1*07:01:01:01_2_rp_T_1_DRB1*07:01:01:01 
         CCCACCTATGAGTGAGAACATGCGGTgtttggttttttgttcttgcgatagtttactgagaatgatgatttccaat
         tTCATCCATGTCCCTACAAAGGACA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 11.1905 ± 0, Mean Tm: 57.4 ± 2.5 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                        

T1: DRB1*07:01:01:01_3    11.1905       101       59.2 / 55.6    5'-CCCACCTATGAGTGAGAACATGCGG-3' / 5'-TGTCCTTTGTAGGGACATGGATGAA-3'


* Template 1: DRB1*07:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*07:01:01:01_3_fp + DRB1*07:01:01:01_3_rp ==> T1: DRB1*07:01:01:01

           PPC = 100.0%, Size = 101 bp, GC content = 40.6%
           FP: 3'ΔG = -4.3(kcal/mol), Tm = 59.2 (°C)
           RP: 3'ΔG = -1.2(kcal/mol), Tm = 55.6 (°C)
           Binding sites: 19(25/25) ... 119(25/25)
         
         >>>DRB1*07:01:01:01_3_fp
            1                       25
         5' CCCACCTATGAGTGAGAACATGCGG 3'
            |||||||||||||||||||||||||                                               119
         5' CCCACCTATGAGTGAGAACATGCGGtgtttggttt...gatttccaatTTCATCCATGTCCCTACAAAGGACA 3'
            19                                              |||||||||||||||||||||||||
                                                         3' TTCATCCATGTCCCTACAAAGGACA 5'
                                                            25                      1
                                                                 DRB1*07:01:01:01_3_rp<<<
         

         >3_DRB1*07:01:01:01_3_fp_DRB1*07:01:01:01_3_rp_T_1_DRB1*07:01:01:01 
         CCCACCTATGAGTGAGAACATGCGGtgtttggttttttgttcttgcgatagtttactgagaatgatgatttccaat
         TTCATCCATGTCCCTACAAAGGACA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 11.1959 ± 0, Mean Tm: 56.9 ± 2.4 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                       

T1: DRB1*07:01:01:01_4    11.1959       100       58.6 / 55.2    5'-CCACCTATGAGTGAGAACATGCGGT-3' / 5'-TGTCCTTTGTAGGGACATGGATGA-3'


* Template 1: DRB1*07:01:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*07:01:01:01_4_fp + DRB1*07:01:01:01_4_rp ==> T1: DRB1*07:01:01:01

           PPC = 97.1%, Size = 100 bp, GC content = 40.0%
           FP: 3'ΔG = -4.3(kcal/mol), Tm = 58.6 (°C)
           RP: 3'ΔG = -1.6(kcal/mol), Tm = 55.2 (°C)
           Binding sites: 20(25/25) ... 119(24/24)
         
         >>>DRB1*07:01:01:01_4_fp
            1                       25
         5' CCACCTATGAGTGAGAACATGCGGT 3'
            |||||||||||||||||||||||||                                                119
         5' CCACCTATGAGTGAGAACATGCGGTgtttggttttt...gatttccaattTCATCCATGTCCCTACAAAGGACA 3'
            20                                                ||||||||||||||||||||||||
                                                           3' TCATCCATGTCCCTACAAAGGACA 5'
                                                              24                     1
                                                                 DRB1*07:01:01:01_4_rp<<<
         

         >9_DRB1*07:01:01:01_4_fp_DRB1*07:01:01:01_4_rp_T_1_DRB1*07:01:01:01 
         CCACCTATGAGTGAGAACATGCGGTgtttggttttttgttcttgcgatagtttactgagaatgatgatttccaatt
         TCATCCATGTCCCTACAAAGGACA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    