MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DRB1-01region

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [130]                  [59.9/58.6]         2.4674 ± 0 
2              [130]                  [59.9/60.5]         2.5508 ± 0 
3              [130]                  [60.2/58.5]         2.7585 ± 0 
4              [130]                  [60.2/59.4]         2.8686 ± 0 
5              [130]                  [59.0/60.0]         3.0011 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 2.4674 ± 0, Mean Tm: 59.3 ± 0.9 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DRB1-01region_0    2.4674        130       59.9 / 58.6    5'-AGTGTCTTCTCAGGAGGCTGCCC-3' / 5'-TGCATCTTTCCAGCAACCGCAC-3'


* Template 1: DRB1-01region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-01region_0_fp + DRB1-01region_0_rp ==> T1: DRB1-01region

           PPC = 96.9%, Size = 130 bp, GC content = 53.8%
           FP: 3'ΔG = -4.0(kcal/mol), Tm = 59.9 (°C)
           RP: 3'ΔG = -4.0(kcal/mol), Tm = 58.6 (°C)
           Binding sites: 9(23/23) ... 138(22/22)
         
         >>>DRB1-01region_0_fp
            1                     23
         5' AGTGTCTTCTCAGGAGGCTGCCC 3'
            |||||||||||||||||||||||                                                  138
         5' AGTGTCTTCTCAGGAGGCTGCCCgtgtgaccggatc...tgggacggagcggGTGCGGTTGCTGGAAAGATGCA 3'
            9                                                   ||||||||||||||||||||||
                                                             3' GTGCGGTTGCTGGAAAGATGCA 5'
                                                                22                   1
                                                                    DRB1-01region_0_rp<<<
         

         >18_DRB1-01region_0_fp_DRB1-01region_0_rp_T_1_DRB1-01region 
         AGTGTCTTCTCAGGAGGCTGCCCgtgtgaccggatccttcgtgtccccacagcacgtttcttgtggcagcttaagt
         ttgaatgtcatttcttcaatgggacggagcggGTGCGGTTGCTGGAAAGATGCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 2.5508 ± 0, Mean Tm: 60.2 ± 0.4 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DRB1-01region_1    2.5508        130       59.9 / 60.5    5'-AGTGTCTTCTCAGGAGGCTGCCC-3' / 5'-TGCATCTTTCCAGCAACCGCACC-3'


* Template 1: DRB1-01region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-01region_1_fp + DRB1-01region_1_rp ==> T1: DRB1-01region

           PPC = 100.0%, Size = 130 bp, GC content = 53.8%
           FP: 3'ΔG = -4.0(kcal/mol), Tm = 59.9 (°C)
           RP: 3'ΔG = -3.7(kcal/mol), Tm = 60.5 (°C)
           Binding sites: 9(23/23) ... 138(23/23)
         
         >>>DRB1-01region_1_fp
            1                     23
         5' AGTGTCTTCTCAGGAGGCTGCCC 3'
            |||||||||||||||||||||||                                                 138
         5' AGTGTCTTCTCAGGAGGCTGCCCgtgtgaccggat...tgggacggagcgGGTGCGGTTGCTGGAAAGATGCA 3'
            9                                                 |||||||||||||||||||||||
                                                           3' GGTGCGGTTGCTGGAAAGATGCA 5'
                                                              23                    1
                                                                    DRB1-01region_1_rp<<<
         

         >6_DRB1-01region_1_fp_DRB1-01region_1_rp_T_1_DRB1-01region 
         AGTGTCTTCTCAGGAGGCTGCCCgtgtgaccggatccttcgtgtccccacagcacgtttcttgtggcagcttaagt
         ttgaatgtcatttcttcaatgggacggagcgGGTGCGGTTGCTGGAAAGATGCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 2.7585 ± 0, Mean Tm: 59.4 ± 1.2 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DRB1-01region_2    2.7585        130       60.2 / 58.5    5'-TGTCTTCTCAGGAGGCTGCCCG-3' / 5'-GATGCATCTTTCCAGCAACCGCA-3'


* Template 1: DRB1-01region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-01region_2_fp + DRB1-01region_2_rp ==> T1: DRB1-01region

           PPC = 96.9%, Size = 130 bp, GC content = 53.8%
           FP: 3'ΔG = -4.7(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -4.3(kcal/mol), Tm = 58.5 (°C)
           Binding sites: 11(22/22) ... 140(23/23)
         
         >>>DRB1-01region_2_fp
            1                    22
         5' TGTCTTCTCAGGAGGCTGCCCG 3'
            ||||||||||||||||||||||                                                   140
         5' TGTCTTCTCAGGAGGCTGCCCGtgtgaccggatcc...gggacggagcgggTGCGGTTGCTGGAAAGATGCATC 3'
            11                                                 |||||||||||||||||||||||
                                                            3' TGCGGTTGCTGGAAAGATGCATC 5'
                                                               23                    1
                                                                    DRB1-01region_2_rp<<<
         

         >20_DRB1-01region_2_fp_DRB1-01region_2_rp_T_1_DRB1-01region 
         TGTCTTCTCAGGAGGCTGCCCGtgtgaccggatccttcgtgtccccacagcacgtttcttgtggcagcttaagttt
         gaatgtcatttcttcaatgggacggagcgggTGCGGTTGCTGGAAAGATGCATC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 2.8686 ± 0, Mean Tm: 59.8 ± 0.6 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DRB1-01region_3    2.8686        130       60.2 / 59.4    5'-TGTCTTCTCAGGAGGCTGCCCG-3' / 5'-GATGCATCTTTCCAGCAACCGCAC-3'


* Template 1: DRB1-01region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-01region_3_fp + DRB1-01region_3_rp ==> T1: DRB1-01region

           PPC = 93.9%, Size = 130 bp, GC content = 53.8%
           FP: 3'ΔG = -4.7(kcal/mol), Tm = 60.2 (°C)
           RP: 3'ΔG = -4.0(kcal/mol), Tm = 59.4 (°C)
           Binding sites: 11(22/22) ... 140(24/24)
         
         >>>DRB1-01region_3_fp
            1                    22
         5' TGTCTTCTCAGGAGGCTGCCCG 3'
            ||||||||||||||||||||||                                                  140
         5' TGTCTTCTCAGGAGGCTGCCCGtgtgaccggatc...gggacggagcggGTGCGGTTGCTGGAAAGATGCATC 3'
            11                                               ||||||||||||||||||||||||
                                                          3' GTGCGGTTGCTGGAAAGATGCATC 5'
                                                             24                     1
                                                                    DRB1-01region_3_rp<<<
         

         >23_DRB1-01region_3_fp_DRB1-01region_3_rp_T_1_DRB1-01region 
         TGTCTTCTCAGGAGGCTGCCCGtgtgaccggatccttcgtgtccccacagcacgtttcttgtggcagcttaagttt
         gaatgtcatttcttcaatgggacggagcggGTGCGGTTGCTGGAAAGATGCATC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 3.0011 ± 0, Mean Tm: 59.5 ± 0.7 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                    

T1: DRB1-01region_4    3.0011        130       59.0 / 60.0    5'-GTCAGTGTCTTCTCAGGAGGCTGC-3' / 5'-ATCTTTCCAGCAACCGCACCCG-3'


* Template 1: DRB1-01region

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1-01region_4_fp + DRB1-01region_4_rp ==> T1: DRB1-01region

           PPC = 93.9%, Size = 130 bp, GC content = 53.8%
           FP: 3'ΔG = -3.9(kcal/mol), Tm = 59.0 (°C)
           RP: 3'ΔG = -3.9(kcal/mol), Tm = 60.0 (°C)
           Binding sites: 6(24/24) ... 135(22/22)
         
         >>>DRB1-01region_4_fp
            1                      24
         5' GTCAGTGTCTTCTCAGGAGGCTGC 3'
            ||||||||||||||||||||||||                                                135
         5' GTCAGTGTCTTCTCAGGAGGCTGCccgtgtgaccgg...aatgggacggagCGGGTGCGGTTGCTGGAAAGAT 3'
            6                                                  ||||||||||||||||||||||
                                                            3' CGGGTGCGGTTGCTGGAAAGAT 5'
                                                               22                   1
                                                                    DRB1-01region_4_rp<<<
         

         >24_DRB1-01region_4_fp_DRB1-01region_4_rp_T_1_DRB1-01region 
         GTCAGTGTCTTCTCAGGAGGCTGCccgtgtgaccggatccttcgtgtccccacagcacgtttcttgtggcagctta
         agtttgaatgtcatttcttcaatgggacggagCGGGTGCGGTTGCTGGAAAGAT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    