MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DRB1*08:02:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [107]                  [59.7/60.2]         0.4411 ± 0 
2              [105]                  [59.7/59.5]         0.7482 ± 0 
3              [109]                  [59.7/60.8]         1.0259 ± 0 
4              [106]                  [59.7/59.1]         1.1160 ± 0 
5              [106]                  [60.0/60.2]         1.1821 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 0.4411 ± 0, Mean Tm: 60.0 ± 0.3 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*08:02:01:01_0    0.4411        107       59.7 / 60.2    5'-TGGTGCAATCTCGGCTCACTGC-3' / 5'-CCAGGTATGGTGGTGGGTGCCT-3'


* Template 1: DRB1*08:02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*08:02:01:01_0_fp + DRB1*08:02:01:01_0_rp ==> T1: DRB1*08:02:01:01

           PPC = 100.0%, Size = 107 bp, GC content = 54.7%
           FP: 3'ΔG = -3.1(kcal/mol), Tm = 59.7 (°C)
           RP: 3'ΔG = -3.4(kcal/mol), Tm = 60.2 (°C)
           Binding sites: 3(22/22) ... 109(22/22)
         
         >>>DRB1*08:02:01:01_0_fp
            1                    22
         5' TGGTGCAATCTCGGCTCACTGC 3'
            ||||||||||||||||||||||                                                  109
         5' TGGTGCAATCTCGGCTCACTGCaaccttcgcctcc...atctgagattnacAGGCACCCACCACCATACCTGG 3'
            3                                                  ||||||||||||||||||||||
                                                            3' AGGCACCCACCACCATACCTGG 5'
                                                               22                   1
                                                                 DRB1*08:02:01:01_0_rp<<<
         

         >9_DRB1*08:02:01:01_0_fp_DRB1*08:02:01:01_0_rp_T_1_DRB1*08:02:01:01 
         TGGTGCAATCTCGGCTCACTGCaaccttcgcctccctggttcaagtgattctcctgcctcagcttcccaagtatct
         gagattnacAGGCACCCACCACCATACCTGG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 0.7482 ± 0, Mean Tm: 59.6 ± 0.2 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*08:02:01:01_1    0.7482        105       59.7 / 59.5    5'-TGGTGCAATCTCGGCTCACTGC-3' / 5'-AGGTATGGTGGTGGGTGCCTGT-3'


* Template 1: DRB1*08:02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*08:02:01:01_1_fp + DRB1*08:02:01:01_1_rp ==> T1: DRB1*08:02:01:01

           PPC = 100.0%, Size = 105 bp, GC content = 53.8%
           FP: 3'ΔG = -3.1(kcal/mol), Tm = 59.7 (°C)
           RP: 3'ΔG = -2.7(kcal/mol), Tm = 59.5 (°C)
           Binding sites: 3(22/22) ... 107(22/22)
         
         >>>DRB1*08:02:01:01_1_fp
            1                    22
         5' TGGTGCAATCTCGGCTCACTGC 3'
            ||||||||||||||||||||||                                                  107
         5' TGGTGCAATCTCGGCTCACTGCaaccttcgcctcc...gtatctgagattnACAGGCACCCACCACCATACCT 3'
            3                                                  ||||||||||||||||||||||
                                                            3' ACAGGCACCCACCACCATACCT 5'
                                                               22                   1
                                                                 DRB1*08:02:01:01_1_rp<<<
         

         >2_DRB1*08:02:01:01_1_fp_DRB1*08:02:01:01_1_rp_T_1_DRB1*08:02:01:01 
         TGGTGCAATCTCGGCTCACTGCaaccttcgcctccctggttcaagtgattctcctgcctcagcttcccaagtatct
         gagattnACAGGCACCCACCACCATACCT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 1.0259 ± 0, Mean Tm: 60.2 ± 0.7 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*08:02:01:01_2    1.0259        109       59.7 / 60.8    5'-TGGTGCAATCTCGGCTCACTGC-3' / 5'-AGCCAGGTATGGTGGTGGGTGC-3'


* Template 1: DRB1*08:02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*08:02:01:01_2_fp + DRB1*08:02:01:01_2_rp ==> T1: DRB1*08:02:01:01

           PPC = 100.0%, Size = 109 bp, GC content = 54.6%
           FP: 3'ΔG = -3.1(kcal/mol), Tm = 59.7 (°C)
           RP: 3'ΔG = -3.7(kcal/mol), Tm = 60.8 (°C)
           Binding sites: 3(22/22) ... 111(22/22)
         
         >>>DRB1*08:02:01:01_2_fp
            1                    22
         5' TGGTGCAATCTCGGCTCACTGC 3'
            ||||||||||||||||||||||                                                  111
         5' TGGTGCAATCTCGGCTCACTGCaaccttcgcctcc...ctgagattnacagGCACCCACCACCATACCTGGCT 3'
            3                                                  ||||||||||||||||||||||
                                                            3' GCACCCACCACCATACCTGGCT 5'
                                                               22                   1
                                                                 DRB1*08:02:01:01_2_rp<<<
         

         >19_DRB1*08:02:01:01_2_fp_DRB1*08:02:01:01_2_rp_T_1_DRB1*08:02:01:01 
         TGGTGCAATCTCGGCTCACTGCaaccttcgcctccctggttcaagtgattctcctgcctcagcttcccaagtatct
         gagattnacagGCACCCACCACCATACCTGGCT
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 1.1160 ± 0, Mean Tm: 59.4 ± 0.4 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*08:02:01:01_3    1.116         106       59.7 / 59.1    5'-TGGTGCAATCTCGGCTCACTGC-3' / 5'-CAGGTATGGTGGTGGGTGCCTG-3'


* Template 1: DRB1*08:02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*08:02:01:01_3_fp + DRB1*08:02:01:01_3_rp ==> T1: DRB1*08:02:01:01

           PPC = 100.0%, Size = 106 bp, GC content = 54.2%
           FP: 3'ΔG = -3.1(kcal/mol), Tm = 59.7 (°C)
           RP: 3'ΔG = -3.5(kcal/mol), Tm = 59.1 (°C)
           Binding sites: 3(22/22) ... 108(22/22)
         
         >>>DRB1*08:02:01:01_3_fp
            1                    22
         5' TGGTGCAATCTCGGCTCACTGC 3'
            ||||||||||||||||||||||                                                  108
         5' TGGTGCAATCTCGGCTCACTGCaaccttcgcctcc...tatctgagattnaCAGGCACCCACCACCATACCTG 3'
            3                                                  ||||||||||||||||||||||
                                                            3' CAGGCACCCACCACCATACCTG 5'
                                                               22                   1
                                                                 DRB1*08:02:01:01_3_rp<<<
         

         >8_DRB1*08:02:01:01_3_fp_DRB1*08:02:01:01_3_rp_T_1_DRB1*08:02:01:01 
         TGGTGCAATCTCGGCTCACTGCaaccttcgcctccctggttcaagtgattctcctgcctcagcttcccaagtatct
         gagattnaCAGGCACCCACCACCATACCTG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 1.1821 ± 0, Mean Tm: 60.1 ± 0.1 (°C)

                                     Amplicon       Tm (°C) 
Primer ID                 Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                   

T1: DRB1*08:02:01:01_4    1.1821        106       60.0 / 60.2    5'-GGTGCAATCTCGGCTCACTGCAA-3' / 5'-CCAGGTATGGTGGTGGGTGCCT-3'


* Template 1: DRB1*08:02:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*08:02:01:01_4_fp + DRB1*08:02:01:01_4_rp ==> T1: DRB1*08:02:01:01

           PPC = 96.9%, Size = 106 bp, GC content = 55.2%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 60.0 (°C)
           RP: 3'ΔG = -3.4(kcal/mol), Tm = 60.2 (°C)
           Binding sites: 4(23/23) ... 109(22/22)
         
         >>>DRB1*08:02:01:01_4_fp
            1                     23
         5' GGTGCAATCTCGGCTCACTGCAA 3'
            |||||||||||||||||||||||                                                  109
         5' GGTGCAATCTCGGCTCACTGCAAccttcgcctccct...atctgagattnacAGGCACCCACCACCATACCTGG 3'
            4                                                   ||||||||||||||||||||||
                                                             3' AGGCACCCACCACCATACCTGG 5'
                                                                22                   1
                                                                 DRB1*08:02:01:01_4_rp<<<
         

         >24_DRB1*08:02:01:01_4_fp_DRB1*08:02:01:01_4_rp_T_1_DRB1*08:02:01:01 
         GGTGCAATCTCGGCTCACTGCAAccttcgcctccctggttcaagtgattctcctgcctcagcttcccaagtatctg
         agattnacAGGCACCCACCACCATACCTGG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    