MPprimer-1.4 [Jun 10, 2010]

Zhiyong Shen*, Wubin Qu*, Wen Wang, Yiming Lu, Yonghong Wu, Zhifeng Li, Xingyi Hang, 
Xiaolei Wang, Dongsheng Zhao, Chenggang Zhang. MPprimer: a program for reliable 
multiplex PCR primer design. BMC Bioinformatics, 2010, 11:143. (Join first author)


****************************************************************************************************
Template sequence (1)
    Template 1: DRB1*15:01:01

PSC (Primer Set Combination): 5
Database used for specificity checking: None
MinBS: 2mm
MFEprimer performance: Word size 11, E-value 1000
Total time used: 0 m 0 s
****************************************************************************************************

Short description of 5 PSCs (Primer Set Combinations) sorted by the mean penalty of the primer set combinations

PSC    Size distribution (bp)    Tm distribution (°C)    Mean penalty

1              [131]                  [59.0/60.0]         1.0239 ± 0 
2              [158]                  [59.0/59.9]         1.0950 ± 0 
3              [155]                  [59.0/59.9]         1.0956 ± 0 
4              [132]                  [59.0/60.4]         1.3834 ± 0 
5              [134]                  [59.0/59.6]         1.4114 ± 0 



Details of the 5 PSCs sorted by the mean penalty of the primer set combinations


****************************************************************************************************

PSC 1: Mean penalty: 1.0239 ± 0, Mean Tm: 59.5 ± 0.7 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*15:01:01_0    1.0239        131       59.0 / 60.0    5'-TGGTGAGGCTAGGGCTTCAGGT-3' / 5'-GCTGGCCTGTGCCCTCTTCTTG-3'


* Template 1: DRB1*15:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*15:01:01_0_fp + DRB1*15:01:01_0_rp ==> T1: DRB1*15:01:01

           PPC = 100.0%, Size = 131 bp, GC content = 48.1%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.0 (°C)
           RP: 3'ΔG = -1.7(kcal/mol), Tm = 60.0 (°C)
           Binding sites: 2(22/22) ... 132(22/22)
         
         >>>DRB1*15:01:01_0_fp
            1                    22
         5' TGGTGAGGCTAGGGCTTCAGGT 3'
            ||||||||||||||||||||||                                                  132
         5' TGGTGAGGCTAGGGCTTCAGGTatttatgttggag...ttgtgtggagaaaCAAGAAGAGGGCACAGGCCAGC 3'
            2                                                  ||||||||||||||||||||||
                                                            3' CAAGAAGAGGGCACAGGCCAGC 5'
                                                               22                   1
                                                                    DRB1*15:01:01_0_rp<<<
         

         >1_DRB1*15:01:01_0_fp_DRB1*15:01:01_0_rp_T_1_DRB1*15:01:01 
         TGGTGAGGCTAGGGCTTCAGGTatttatgttggaggcatcaatacgtgtagtgtgttaaattccagggagtggaag
         aggatacatagggagatggattgtgtggagaaaCAAGAAGAGGGCACAGGCCAGC
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 2: Mean penalty: 1.0950 ± 0, Mean Tm: 59.5 ± 0.7 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*15:01:01_1    1.095         158       59.0 / 59.9    5'-TGGTGAGGCTAGGGCTTCAGGT-3' / 5'-TCCCTGGGCTCTTTCTCAGCCC-3'


* Template 1: DRB1*15:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*15:01:01_1_fp + DRB1*15:01:01_1_rp ==> T1: DRB1*15:01:01

           PPC = 100.0%, Size = 158 bp, GC content = 50.0%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.0 (°C)
           RP: 3'ΔG = -3.8(kcal/mol), Tm = 59.9 (°C)
           Binding sites: 2(22/22) ... 159(22/22)
         
         >>>DRB1*15:01:01_1_fp
            1                    22
         5' TGGTGAGGCTAGGGCTTCAGGT 3'
            ||||||||||||||||||||||                                                  159
         5' TGGTGAGGCTAGGGCTTCAGGTatttatgttggag...aggccagcaaaggGGGCTGAGAAAGAGCCCAGGGA 3'
            2                                                  ||||||||||||||||||||||
                                                            3' GGGCTGAGAAAGAGCCCAGGGA 5'
                                                               22                   1
                                                                    DRB1*15:01:01_1_rp<<<
         

         >22_DRB1*15:01:01_1_fp_DRB1*15:01:01_1_rp_T_1_DRB1*15:01:01 
         TGGTGAGGCTAGGGCTTCAGGTatttatgttggaggcatcaatacgtgtagtgtgttaaattccagggagtggaag
         aggatacatagggagatggattgtgtggagaaacaagaagagggcacaggccagcaaaggGGGCTGAGAAAGAGCC
         CAGGGA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 3: Mean penalty: 1.0956 ± 0, Mean Tm: 59.5 ± 0.7 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*15:01:01_2    1.0956        155       59.0 / 59.9    5'-TGGTGAGGCTAGGGCTTCAGGT-3' / 5'-CTGGGCTCTTTCTCAGCCCCCT-3'


* Template 1: DRB1*15:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*15:01:01_2_fp + DRB1*15:01:01_2_rp ==> T1: DRB1*15:01:01

           PPC = 100.0%, Size = 155 bp, GC content = 49.7%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.0 (°C)
           RP: 3'ΔG = -3.4(kcal/mol), Tm = 59.9 (°C)
           Binding sites: 2(22/22) ... 156(22/22)
         
         >>>DRB1*15:01:01_2_fp
            1                    22
         5' TGGTGAGGCTAGGGCTTCAGGT 3'
            ||||||||||||||||||||||                                                  156
         5' TGGTGAGGCTAGGGCTTCAGGTatttatgttggag...cacaggccagcaaAGGGGGCTGAGAAAGAGCCCAG 3'
            2                                                  ||||||||||||||||||||||
                                                            3' AGGGGGCTGAGAAAGAGCCCAG 5'
                                                               22                   1
                                                                    DRB1*15:01:01_2_rp<<<
         

         >18_DRB1*15:01:01_2_fp_DRB1*15:01:01_2_rp_T_1_DRB1*15:01:01 
         TGGTGAGGCTAGGGCTTCAGGTatttatgttggaggcatcaatacgtgtagtgtgttaaattccagggagtggaag
         aggatacatagggagatggattgtgtggagaaacaagaagagggcacaggccagcaaAGGGGGCTGAGAAAGAGCC
         CAG
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 4: Mean penalty: 1.3834 ± 0, Mean Tm: 59.7 ± 1.0 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*15:01:01_3    1.3834        132       59.0 / 60.4    5'-TGGTGAGGCTAGGGCTTCAGGT-3' / 5'-TGCTGGCCTGTGCCCTCTTCTT-3'


* Template 1: DRB1*15:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*15:01:01_3_fp + DRB1*15:01:01_3_rp ==> T1: DRB1*15:01:01

           PPC = 100.0%, Size = 132 bp, GC content = 47.7%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.0 (°C)
           RP: 3'ΔG = -1.2(kcal/mol), Tm = 60.4 (°C)
           Binding sites: 2(22/22) ... 133(22/22)
         
         >>>DRB1*15:01:01_3_fp
            1                    22
         5' TGGTGAGGCTAGGGCTTCAGGT 3'
            ||||||||||||||||||||||                                                  133
         5' TGGTGAGGCTAGGGCTTCAGGTatttatgttggag...tgtgtggagaaacAAGAAGAGGGCACAGGCCAGCA 3'
            2                                                  ||||||||||||||||||||||
                                                            3' AAGAAGAGGGCACAGGCCAGCA 5'
                                                               22                   1
                                                                    DRB1*15:01:01_3_rp<<<
         

         >9_DRB1*15:01:01_3_fp_DRB1*15:01:01_3_rp_T_1_DRB1*15:01:01 
         TGGTGAGGCTAGGGCTTCAGGTatttatgttggaggcatcaatacgtgtagtgtgttaaattccagggagtggaag
         aggatacatagggagatggattgtgtggagaaacAAGAAGAGGGCACAGGCCAGCA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


****************************************************************************************************

PSC 5: Mean penalty: 1.4114 ± 0, Mean Tm: 59.3 ± 0.4 (°C)

                                  Amplicon       Tm (°C) 
Primer ID              Penalty    size (bp)      (FP/RP)      Forward primer (FP) / Reverse primer (RP)                  

T1: DRB1*15:01:01_4    1.4114        134       59.0 / 59.6    5'-TGGTGAGGCTAGGGCTTCAGGT-3' / 5'-TTTGCTGGCCTGTGCCCTCTTC-3'


* Template 1: DRB1*15:01:01

   ** Diagram of the binding pattern between the primers and the template

     *** DRB1*15:01:01_4_fp + DRB1*15:01:01_4_rp ==> T1: DRB1*15:01:01

           PPC = 100.0%, Size = 134 bp, GC content = 47.0%
           FP: 3'ΔG = -2.7(kcal/mol), Tm = 59.0 (°C)
           RP: 3'ΔG = -1.6(kcal/mol), Tm = 59.6 (°C)
           Binding sites: 2(22/22) ... 135(22/22)
         
         >>>DRB1*15:01:01_4_fp
            1                    22
         5' TGGTGAGGCTAGGGCTTCAGGT 3'
            ||||||||||||||||||||||                                                  135
         5' TGGTGAGGCTAGGGCTTCAGGTatttatgttggag...tgtggagaaacaaGAAGAGGGCACAGGCCAGCAAA 3'
            2                                                  ||||||||||||||||||||||
                                                            3' GAAGAGGGCACAGGCCAGCAAA 5'
                                                               22                   1
                                                                    DRB1*15:01:01_4_rp<<<
         

         >15_DRB1*15:01:01_4_fp_DRB1*15:01:01_4_rp_T_1_DRB1*15:01:01 
         TGGTGAGGCTAGGGCTTCAGGTatttatgttggaggcatcaatacgtgtagtgtgttaaattccagggagtggaag
         aggatacatagggagatggattgtgtggagaaacaaGAAGAGGGCACAGGCCAGCAAA
         
   ** MFEprimer specificity checking result

         No MFEprimer specificity checking result is available


References

    Qu, W., Shen, Z., Zhao, D., Yang, Y. and Zhang, C. (2009) MFEprimer: 
    multiple factor evaluation of the specificity of PCR primers, 
    Bioinformatics, 25, 276-278.
    
    Altschul, S.F., Madden, T.L., Schaffer, A.A., Zhang, J., Zhang, Z., Miller, W. 
    and Lipman, D.J. (1997) Gapped BLAST and PSI-BLAST: a new generation of protein
    database search programs, Nucleic Acids Res, 25, 3389-3402.
    